// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {
  pub const SW_EthIpUdpHeaders_BYTE_SIZE: usize = 42;
  pub const SW_EthIpUdpHeaders_DIM_0: usize = 42;

  pub type EthIpUdpHeaders = [u8; SW_EthIpUdpHeaders_DIM_0];
}