// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {
  pub const SW_u16Array_BYTE_SIZE: usize = 2;
  pub const SW_u16Array_DIM_0: usize = 1;

  pub type u16Array = [u16; SW_u16Array_DIM_0];
}