// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {
  pub const SW_UdpPayload_BYTE_SIZE: usize = 1558;
  pub const SW_UdpPayload_DIM_0: usize = 1558;

  pub type UdpPayload = [u8; SW_UdpPayload_DIM_0];
}