// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {

  pub trait seL4_RxFirewall_RxFirewall_Api {}

  pub trait seL4_RxFirewall_RxFirewall_Put_Api: seL4_RxFirewall_RxFirewall_Api {
    #[verifier::external_body]
    fn unverified_put_VmmOut0(
      &mut self,
      value: SW::RawEthernetMessage)
    {
      extern_api::unsafe_put_VmmOut0(&value);
    }

    #[verifier::external_body]
    fn unverified_put_VmmOut1(
      &mut self,
      value: SW::RawEthernetMessage)
    {
      extern_api::unsafe_put_VmmOut1(&value);
    }

    #[verifier::external_body]
    fn unverified_put_VmmOut2(
      &mut self,
      value: SW::RawEthernetMessage)
    {
      extern_api::unsafe_put_VmmOut2(&value);
    }

    #[verifier::external_body]
    fn unverified_put_VmmOut3(
      &mut self,
      value: SW::RawEthernetMessage)
    {
      extern_api::unsafe_put_VmmOut3(&value);
    }

    #[verifier::external_body]
    fn unverified_put_MavlinkOut0(
      &mut self,
      value: SW::UdpFrame_Impl)
    {
      extern_api::unsafe_put_MavlinkOut0(&value);
    }

    #[verifier::external_body]
    fn unverified_put_MavlinkOut1(
      &mut self,
      value: SW::UdpFrame_Impl)
    {
      extern_api::unsafe_put_MavlinkOut1(&value);
    }

    #[verifier::external_body]
    fn unverified_put_MavlinkOut2(
      &mut self,
      value: SW::UdpFrame_Impl)
    {
      extern_api::unsafe_put_MavlinkOut2(&value);
    }

    #[verifier::external_body]
    fn unverified_put_MavlinkOut3(
      &mut self,
      value: SW::UdpFrame_Impl)
    {
      extern_api::unsafe_put_MavlinkOut3(&value);
    }
  }

  pub trait seL4_RxFirewall_RxFirewall_Get_Api: seL4_RxFirewall_RxFirewall_Api {
    #[verifier::external_body]
    fn unverified_get_EthernetFramesRxIn0(
      &mut self,
      value: &Ghost<Option<SW::RawEthernetMessage>>) -> (res : Option<SW::RawEthernetMessage>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_EthernetFramesRxIn0();
    }

    #[verifier::external_body]
    fn unverified_get_EthernetFramesRxIn1(
      &mut self,
      value: &Ghost<Option<SW::RawEthernetMessage>>) -> (res : Option<SW::RawEthernetMessage>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_EthernetFramesRxIn1();
    }

    #[verifier::external_body]
    fn unverified_get_EthernetFramesRxIn2(
      &mut self,
      value: &Ghost<Option<SW::RawEthernetMessage>>) -> (res : Option<SW::RawEthernetMessage>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_EthernetFramesRxIn2();
    }

    #[verifier::external_body]
    fn unverified_get_EthernetFramesRxIn3(
      &mut self,
      value: &Ghost<Option<SW::RawEthernetMessage>>) -> (res : Option<SW::RawEthernetMessage>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_EthernetFramesRxIn3();
    }
  }

  pub trait seL4_RxFirewall_RxFirewall_Full_Api: seL4_RxFirewall_RxFirewall_Put_Api + seL4_RxFirewall_RxFirewall_Get_Api {}

  pub struct seL4_RxFirewall_RxFirewall_Application_Api<API: seL4_RxFirewall_RxFirewall_Api> {
    pub api: API,

    pub ghost EthernetFramesRxIn0: Option<SW::RawEthernetMessage>,
    pub ghost EthernetFramesRxIn1: Option<SW::RawEthernetMessage>,
    pub ghost EthernetFramesRxIn2: Option<SW::RawEthernetMessage>,
    pub ghost EthernetFramesRxIn3: Option<SW::RawEthernetMessage>,
    pub ghost VmmOut0: Option<SW::RawEthernetMessage>,
    pub ghost VmmOut1: Option<SW::RawEthernetMessage>,
    pub ghost VmmOut2: Option<SW::RawEthernetMessage>,
    pub ghost VmmOut3: Option<SW::RawEthernetMessage>,
    pub ghost MavlinkOut0: Option<SW::UdpFrame_Impl>,
    pub ghost MavlinkOut1: Option<SW::UdpFrame_Impl>,
    pub ghost MavlinkOut2: Option<SW::UdpFrame_Impl>,
    pub ghost MavlinkOut3: Option<SW::UdpFrame_Impl>
  }

  impl<API: seL4_RxFirewall_RxFirewall_Put_Api> seL4_RxFirewall_RxFirewall_Application_Api<API> {
    pub fn put_VmmOut0(
      &mut self,
      value: SW::RawEthernetMessage)
      ensures
        old(self).EthernetFramesRxIn0 == self.EthernetFramesRxIn0,
        old(self).EthernetFramesRxIn1 == self.EthernetFramesRxIn1,
        old(self).EthernetFramesRxIn2 == self.EthernetFramesRxIn2,
        old(self).EthernetFramesRxIn3 == self.EthernetFramesRxIn3,
        self.VmmOut0 == Some(value),
        old(self).VmmOut1 == self.VmmOut1,
        old(self).VmmOut2 == self.VmmOut2,
        old(self).VmmOut3 == self.VmmOut3,
        old(self).MavlinkOut0 == self.MavlinkOut0,
        old(self).MavlinkOut1 == self.MavlinkOut1,
        old(self).MavlinkOut2 == self.MavlinkOut2,
        old(self).MavlinkOut3 == self.MavlinkOut3,
    {
      self.api.unverified_put_VmmOut0(value);
      self.VmmOut0 = Some(value);
    }
    pub fn put_VmmOut1(
      &mut self,
      value: SW::RawEthernetMessage)
      ensures
        old(self).EthernetFramesRxIn0 == self.EthernetFramesRxIn0,
        old(self).EthernetFramesRxIn1 == self.EthernetFramesRxIn1,
        old(self).EthernetFramesRxIn2 == self.EthernetFramesRxIn2,
        old(self).EthernetFramesRxIn3 == self.EthernetFramesRxIn3,
        old(self).VmmOut0 == self.VmmOut0,
        self.VmmOut1 == Some(value),
        old(self).VmmOut2 == self.VmmOut2,
        old(self).VmmOut3 == self.VmmOut3,
        old(self).MavlinkOut0 == self.MavlinkOut0,
        old(self).MavlinkOut1 == self.MavlinkOut1,
        old(self).MavlinkOut2 == self.MavlinkOut2,
        old(self).MavlinkOut3 == self.MavlinkOut3,
    {
      self.api.unverified_put_VmmOut1(value);
      self.VmmOut1 = Some(value);
    }
    pub fn put_VmmOut2(
      &mut self,
      value: SW::RawEthernetMessage)
      ensures
        old(self).EthernetFramesRxIn0 == self.EthernetFramesRxIn0,
        old(self).EthernetFramesRxIn1 == self.EthernetFramesRxIn1,
        old(self).EthernetFramesRxIn2 == self.EthernetFramesRxIn2,
        old(self).EthernetFramesRxIn3 == self.EthernetFramesRxIn3,
        old(self).VmmOut0 == self.VmmOut0,
        old(self).VmmOut1 == self.VmmOut1,
        self.VmmOut2 == Some(value),
        old(self).VmmOut3 == self.VmmOut3,
        old(self).MavlinkOut0 == self.MavlinkOut0,
        old(self).MavlinkOut1 == self.MavlinkOut1,
        old(self).MavlinkOut2 == self.MavlinkOut2,
        old(self).MavlinkOut3 == self.MavlinkOut3,
    {
      self.api.unverified_put_VmmOut2(value);
      self.VmmOut2 = Some(value);
    }
    pub fn put_VmmOut3(
      &mut self,
      value: SW::RawEthernetMessage)
      ensures
        old(self).EthernetFramesRxIn0 == self.EthernetFramesRxIn0,
        old(self).EthernetFramesRxIn1 == self.EthernetFramesRxIn1,
        old(self).EthernetFramesRxIn2 == self.EthernetFramesRxIn2,
        old(self).EthernetFramesRxIn3 == self.EthernetFramesRxIn3,
        old(self).VmmOut0 == self.VmmOut0,
        old(self).VmmOut1 == self.VmmOut1,
        old(self).VmmOut2 == self.VmmOut2,
        self.VmmOut3 == Some(value),
        old(self).MavlinkOut0 == self.MavlinkOut0,
        old(self).MavlinkOut1 == self.MavlinkOut1,
        old(self).MavlinkOut2 == self.MavlinkOut2,
        old(self).MavlinkOut3 == self.MavlinkOut3,
    {
      self.api.unverified_put_VmmOut3(value);
      self.VmmOut3 = Some(value);
    }
    pub fn put_MavlinkOut0(
      &mut self,
      value: SW::UdpFrame_Impl)
      ensures
        old(self).EthernetFramesRxIn0 == self.EthernetFramesRxIn0,
        old(self).EthernetFramesRxIn1 == self.EthernetFramesRxIn1,
        old(self).EthernetFramesRxIn2 == self.EthernetFramesRxIn2,
        old(self).EthernetFramesRxIn3 == self.EthernetFramesRxIn3,
        old(self).VmmOut0 == self.VmmOut0,
        old(self).VmmOut1 == self.VmmOut1,
        old(self).VmmOut2 == self.VmmOut2,
        old(self).VmmOut3 == self.VmmOut3,
        self.MavlinkOut0 == Some(value),
        old(self).MavlinkOut1 == self.MavlinkOut1,
        old(self).MavlinkOut2 == self.MavlinkOut2,
        old(self).MavlinkOut3 == self.MavlinkOut3,
    {
      self.api.unverified_put_MavlinkOut0(value);
      self.MavlinkOut0 = Some(value);
    }
    pub fn put_MavlinkOut1(
      &mut self,
      value: SW::UdpFrame_Impl)
      ensures
        old(self).EthernetFramesRxIn0 == self.EthernetFramesRxIn0,
        old(self).EthernetFramesRxIn1 == self.EthernetFramesRxIn1,
        old(self).EthernetFramesRxIn2 == self.EthernetFramesRxIn2,
        old(self).EthernetFramesRxIn3 == self.EthernetFramesRxIn3,
        old(self).VmmOut0 == self.VmmOut0,
        old(self).VmmOut1 == self.VmmOut1,
        old(self).VmmOut2 == self.VmmOut2,
        old(self).VmmOut3 == self.VmmOut3,
        old(self).MavlinkOut0 == self.MavlinkOut0,
        self.MavlinkOut1 == Some(value),
        old(self).MavlinkOut2 == self.MavlinkOut2,
        old(self).MavlinkOut3 == self.MavlinkOut3,
    {
      self.api.unverified_put_MavlinkOut1(value);
      self.MavlinkOut1 = Some(value);
    }
    pub fn put_MavlinkOut2(
      &mut self,
      value: SW::UdpFrame_Impl)
      ensures
        old(self).EthernetFramesRxIn0 == self.EthernetFramesRxIn0,
        old(self).EthernetFramesRxIn1 == self.EthernetFramesRxIn1,
        old(self).EthernetFramesRxIn2 == self.EthernetFramesRxIn2,
        old(self).EthernetFramesRxIn3 == self.EthernetFramesRxIn3,
        old(self).VmmOut0 == self.VmmOut0,
        old(self).VmmOut1 == self.VmmOut1,
        old(self).VmmOut2 == self.VmmOut2,
        old(self).VmmOut3 == self.VmmOut3,
        old(self).MavlinkOut0 == self.MavlinkOut0,
        old(self).MavlinkOut1 == self.MavlinkOut1,
        self.MavlinkOut2 == Some(value),
        old(self).MavlinkOut3 == self.MavlinkOut3,
    {
      self.api.unverified_put_MavlinkOut2(value);
      self.MavlinkOut2 = Some(value);
    }
    pub fn put_MavlinkOut3(
      &mut self,
      value: SW::UdpFrame_Impl)
      ensures
        old(self).EthernetFramesRxIn0 == self.EthernetFramesRxIn0,
        old(self).EthernetFramesRxIn1 == self.EthernetFramesRxIn1,
        old(self).EthernetFramesRxIn2 == self.EthernetFramesRxIn2,
        old(self).EthernetFramesRxIn3 == self.EthernetFramesRxIn3,
        old(self).VmmOut0 == self.VmmOut0,
        old(self).VmmOut1 == self.VmmOut1,
        old(self).VmmOut2 == self.VmmOut2,
        old(self).VmmOut3 == self.VmmOut3,
        old(self).MavlinkOut0 == self.MavlinkOut0,
        old(self).MavlinkOut1 == self.MavlinkOut1,
        old(self).MavlinkOut2 == self.MavlinkOut2,
        self.MavlinkOut3 == Some(value),
    {
      self.api.unverified_put_MavlinkOut3(value);
      self.MavlinkOut3 = Some(value);
    }
  }

  impl<API: seL4_RxFirewall_RxFirewall_Get_Api> seL4_RxFirewall_RxFirewall_Application_Api<API> {
    pub fn get_EthernetFramesRxIn0(&mut self) -> (res : Option<SW::RawEthernetMessage>)
      ensures
        old(self).EthernetFramesRxIn0 == self.EthernetFramesRxIn0,
        res == self.EthernetFramesRxIn0,
        old(self).EthernetFramesRxIn1 == self.EthernetFramesRxIn1,
        old(self).EthernetFramesRxIn2 == self.EthernetFramesRxIn2,
        old(self).EthernetFramesRxIn3 == self.EthernetFramesRxIn3,
        old(self).VmmOut0 == self.VmmOut0,
        old(self).VmmOut1 == self.VmmOut1,
        old(self).VmmOut2 == self.VmmOut2,
        old(self).VmmOut3 == self.VmmOut3,
        old(self).MavlinkOut0 == self.MavlinkOut0,
        old(self).MavlinkOut1 == self.MavlinkOut1,
        old(self).MavlinkOut2 == self.MavlinkOut2,
        old(self).MavlinkOut3 == self.MavlinkOut3,
    {
      self.api.unverified_get_EthernetFramesRxIn0(&Ghost(self.EthernetFramesRxIn0))
    }
    pub fn get_EthernetFramesRxIn1(&mut self) -> (res : Option<SW::RawEthernetMessage>)
      ensures
        old(self).EthernetFramesRxIn0 == self.EthernetFramesRxIn0,
        old(self).EthernetFramesRxIn1 == self.EthernetFramesRxIn1,
        res == self.EthernetFramesRxIn1,
        old(self).EthernetFramesRxIn2 == self.EthernetFramesRxIn2,
        old(self).EthernetFramesRxIn3 == self.EthernetFramesRxIn3,
        old(self).VmmOut0 == self.VmmOut0,
        old(self).VmmOut1 == self.VmmOut1,
        old(self).VmmOut2 == self.VmmOut2,
        old(self).VmmOut3 == self.VmmOut3,
        old(self).MavlinkOut0 == self.MavlinkOut0,
        old(self).MavlinkOut1 == self.MavlinkOut1,
        old(self).MavlinkOut2 == self.MavlinkOut2,
        old(self).MavlinkOut3 == self.MavlinkOut3,
    {
      self.api.unverified_get_EthernetFramesRxIn1(&Ghost(self.EthernetFramesRxIn1))
    }
    pub fn get_EthernetFramesRxIn2(&mut self) -> (res : Option<SW::RawEthernetMessage>)
      ensures
        old(self).EthernetFramesRxIn0 == self.EthernetFramesRxIn0,
        old(self).EthernetFramesRxIn1 == self.EthernetFramesRxIn1,
        old(self).EthernetFramesRxIn2 == self.EthernetFramesRxIn2,
        res == self.EthernetFramesRxIn2,
        old(self).EthernetFramesRxIn3 == self.EthernetFramesRxIn3,
        old(self).VmmOut0 == self.VmmOut0,
        old(self).VmmOut1 == self.VmmOut1,
        old(self).VmmOut2 == self.VmmOut2,
        old(self).VmmOut3 == self.VmmOut3,
        old(self).MavlinkOut0 == self.MavlinkOut0,
        old(self).MavlinkOut1 == self.MavlinkOut1,
        old(self).MavlinkOut2 == self.MavlinkOut2,
        old(self).MavlinkOut3 == self.MavlinkOut3,
    {
      self.api.unverified_get_EthernetFramesRxIn2(&Ghost(self.EthernetFramesRxIn2))
    }
    pub fn get_EthernetFramesRxIn3(&mut self) -> (res : Option<SW::RawEthernetMessage>)
      ensures
        old(self).EthernetFramesRxIn0 == self.EthernetFramesRxIn0,
        old(self).EthernetFramesRxIn1 == self.EthernetFramesRxIn1,
        old(self).EthernetFramesRxIn2 == self.EthernetFramesRxIn2,
        old(self).EthernetFramesRxIn3 == self.EthernetFramesRxIn3,
        res == self.EthernetFramesRxIn3,
        old(self).VmmOut0 == self.VmmOut0,
        old(self).VmmOut1 == self.VmmOut1,
        old(self).VmmOut2 == self.VmmOut2,
        old(self).VmmOut3 == self.VmmOut3,
        old(self).MavlinkOut0 == self.MavlinkOut0,
        old(self).MavlinkOut1 == self.MavlinkOut1,
        old(self).MavlinkOut2 == self.MavlinkOut2,
        old(self).MavlinkOut3 == self.MavlinkOut3,
    {
      self.api.unverified_get_EthernetFramesRxIn3(&Ghost(self.EthernetFramesRxIn3))
    }
  }

  pub struct seL4_RxFirewall_RxFirewall_Initialization_Api;
  impl seL4_RxFirewall_RxFirewall_Api for seL4_RxFirewall_RxFirewall_Initialization_Api {}
  impl seL4_RxFirewall_RxFirewall_Put_Api for seL4_RxFirewall_RxFirewall_Initialization_Api {}

  pub const fn init_api() -> seL4_RxFirewall_RxFirewall_Application_Api<seL4_RxFirewall_RxFirewall_Initialization_Api> {
    return seL4_RxFirewall_RxFirewall_Application_Api {
      api: seL4_RxFirewall_RxFirewall_Initialization_Api {},

      EthernetFramesRxIn0: None,
      EthernetFramesRxIn1: None,
      EthernetFramesRxIn2: None,
      EthernetFramesRxIn3: None,
      VmmOut0: None,
      VmmOut1: None,
      VmmOut2: None,
      VmmOut3: None,
      MavlinkOut0: None,
      MavlinkOut1: None,
      MavlinkOut2: None,
      MavlinkOut3: None
    }
  }

  pub struct seL4_RxFirewall_RxFirewall_Compute_Api;
  impl seL4_RxFirewall_RxFirewall_Api for seL4_RxFirewall_RxFirewall_Compute_Api {}
  impl seL4_RxFirewall_RxFirewall_Put_Api for seL4_RxFirewall_RxFirewall_Compute_Api {}
  impl seL4_RxFirewall_RxFirewall_Get_Api for seL4_RxFirewall_RxFirewall_Compute_Api {}
  impl seL4_RxFirewall_RxFirewall_Full_Api for seL4_RxFirewall_RxFirewall_Compute_Api {}

  pub const fn compute_api() -> seL4_RxFirewall_RxFirewall_Application_Api<seL4_RxFirewall_RxFirewall_Compute_Api> {
    return seL4_RxFirewall_RxFirewall_Application_Api {
      api: seL4_RxFirewall_RxFirewall_Compute_Api {},

      EthernetFramesRxIn0: None,
      EthernetFramesRxIn1: None,
      EthernetFramesRxIn2: None,
      EthernetFramesRxIn3: None,
      VmmOut0: None,
      VmmOut1: None,
      VmmOut2: None,
      VmmOut3: None,
      MavlinkOut0: None,
      MavlinkOut1: None,
      MavlinkOut2: None,
      MavlinkOut3: None
    }
  }

}