#include "seL4_ArduPilot_ArduPilot.h"

// Do not edit this file as it will be overwritten if codegen is rerun

void seL4_ArduPilot_ArduPilot_initialize(void);
void seL4_ArduPilot_ArduPilot_notify(microkit_channel channel);
void seL4_ArduPilot_ArduPilot_timeTriggered(void);

volatile sb_queue_SW_RawEthernetMessage_1_t *EthernetFramesTx0_queue_1;
volatile sb_queue_SW_RawEthernetMessage_1_t *EthernetFramesTx1_queue_1;
volatile sb_queue_SW_RawEthernetMessage_1_t *EthernetFramesTx2_queue_1;
volatile sb_queue_SW_RawEthernetMessage_1_t *EthernetFramesTx3_queue_1;
volatile sb_queue_SW_RawEthernetMessage_1_t *MavlinkRx0_queue_1;
sb_queue_SW_RawEthernetMessage_1_Recv_t MavlinkRx0_recv_queue;
volatile sb_queue_SW_RawEthernetMessage_1_t *MavlinkRx1_queue_1;
sb_queue_SW_RawEthernetMessage_1_Recv_t MavlinkRx1_recv_queue;
volatile sb_queue_SW_RawEthernetMessage_1_t *MavlinkRx2_queue_1;
sb_queue_SW_RawEthernetMessage_1_Recv_t MavlinkRx2_recv_queue;
volatile sb_queue_SW_RawEthernetMessage_1_t *MavlinkRx3_queue_1;
sb_queue_SW_RawEthernetMessage_1_Recv_t MavlinkRx3_recv_queue;
volatile sb_queue_SW_RawEthernetMessage_1_t *FirewallRx0_queue_1;
sb_queue_SW_RawEthernetMessage_1_Recv_t FirewallRx0_recv_queue;
volatile sb_queue_SW_RawEthernetMessage_1_t *FirewallRx1_queue_1;
sb_queue_SW_RawEthernetMessage_1_Recv_t FirewallRx1_recv_queue;
volatile sb_queue_SW_RawEthernetMessage_1_t *FirewallRx2_queue_1;
sb_queue_SW_RawEthernetMessage_1_Recv_t FirewallRx2_recv_queue;
volatile sb_queue_SW_RawEthernetMessage_1_t *FirewallRx3_queue_1;
sb_queue_SW_RawEthernetMessage_1_Recv_t FirewallRx3_recv_queue;

#define PORT_FROM_MON 60

bool put_EthernetFramesTx0(const SW_RawEthernetMessage *data) {
  sb_queue_SW_RawEthernetMessage_1_enqueue((sb_queue_SW_RawEthernetMessage_1_t *) EthernetFramesTx0_queue_1, (SW_RawEthernetMessage *) data);

  return true;
}

bool put_EthernetFramesTx1(const SW_RawEthernetMessage *data) {
  sb_queue_SW_RawEthernetMessage_1_enqueue((sb_queue_SW_RawEthernetMessage_1_t *) EthernetFramesTx1_queue_1, (SW_RawEthernetMessage *) data);

  return true;
}

bool put_EthernetFramesTx2(const SW_RawEthernetMessage *data) {
  sb_queue_SW_RawEthernetMessage_1_enqueue((sb_queue_SW_RawEthernetMessage_1_t *) EthernetFramesTx2_queue_1, (SW_RawEthernetMessage *) data);

  return true;
}

bool put_EthernetFramesTx3(const SW_RawEthernetMessage *data) {
  sb_queue_SW_RawEthernetMessage_1_enqueue((sb_queue_SW_RawEthernetMessage_1_t *) EthernetFramesTx3_queue_1, (SW_RawEthernetMessage *) data);

  return true;
}

bool MavlinkRx0_is_empty(void) {
  return sb_queue_SW_RawEthernetMessage_1_is_empty(&MavlinkRx0_recv_queue);
}

bool get_MavlinkRx0_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data) {
  return sb_queue_SW_RawEthernetMessage_1_dequeue((sb_queue_SW_RawEthernetMessage_1_Recv_t *) &MavlinkRx0_recv_queue, numDropped, data);
}

bool get_MavlinkRx0(SW_RawEthernetMessage *data) {
  sb_event_counter_t numDropped;
  return get_MavlinkRx0_poll (&numDropped, data);
}

bool MavlinkRx1_is_empty(void) {
  return sb_queue_SW_RawEthernetMessage_1_is_empty(&MavlinkRx1_recv_queue);
}

bool get_MavlinkRx1_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data) {
  return sb_queue_SW_RawEthernetMessage_1_dequeue((sb_queue_SW_RawEthernetMessage_1_Recv_t *) &MavlinkRx1_recv_queue, numDropped, data);
}

bool get_MavlinkRx1(SW_RawEthernetMessage *data) {
  sb_event_counter_t numDropped;
  return get_MavlinkRx1_poll (&numDropped, data);
}

bool MavlinkRx2_is_empty(void) {
  return sb_queue_SW_RawEthernetMessage_1_is_empty(&MavlinkRx2_recv_queue);
}

bool get_MavlinkRx2_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data) {
  return sb_queue_SW_RawEthernetMessage_1_dequeue((sb_queue_SW_RawEthernetMessage_1_Recv_t *) &MavlinkRx2_recv_queue, numDropped, data);
}

bool get_MavlinkRx2(SW_RawEthernetMessage *data) {
  sb_event_counter_t numDropped;
  return get_MavlinkRx2_poll (&numDropped, data);
}

bool MavlinkRx3_is_empty(void) {
  return sb_queue_SW_RawEthernetMessage_1_is_empty(&MavlinkRx3_recv_queue);
}

bool get_MavlinkRx3_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data) {
  return sb_queue_SW_RawEthernetMessage_1_dequeue((sb_queue_SW_RawEthernetMessage_1_Recv_t *) &MavlinkRx3_recv_queue, numDropped, data);
}

bool get_MavlinkRx3(SW_RawEthernetMessage *data) {
  sb_event_counter_t numDropped;
  return get_MavlinkRx3_poll (&numDropped, data);
}

bool FirewallRx0_is_empty(void) {
  return sb_queue_SW_RawEthernetMessage_1_is_empty(&FirewallRx0_recv_queue);
}

bool get_FirewallRx0_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data) {
  return sb_queue_SW_RawEthernetMessage_1_dequeue((sb_queue_SW_RawEthernetMessage_1_Recv_t *) &FirewallRx0_recv_queue, numDropped, data);
}

bool get_FirewallRx0(SW_RawEthernetMessage *data) {
  sb_event_counter_t numDropped;
  return get_FirewallRx0_poll (&numDropped, data);
}

bool FirewallRx1_is_empty(void) {
  return sb_queue_SW_RawEthernetMessage_1_is_empty(&FirewallRx1_recv_queue);
}

bool get_FirewallRx1_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data) {
  return sb_queue_SW_RawEthernetMessage_1_dequeue((sb_queue_SW_RawEthernetMessage_1_Recv_t *) &FirewallRx1_recv_queue, numDropped, data);
}

bool get_FirewallRx1(SW_RawEthernetMessage *data) {
  sb_event_counter_t numDropped;
  return get_FirewallRx1_poll (&numDropped, data);
}

bool FirewallRx2_is_empty(void) {
  return sb_queue_SW_RawEthernetMessage_1_is_empty(&FirewallRx2_recv_queue);
}

bool get_FirewallRx2_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data) {
  return sb_queue_SW_RawEthernetMessage_1_dequeue((sb_queue_SW_RawEthernetMessage_1_Recv_t *) &FirewallRx2_recv_queue, numDropped, data);
}

bool get_FirewallRx2(SW_RawEthernetMessage *data) {
  sb_event_counter_t numDropped;
  return get_FirewallRx2_poll (&numDropped, data);
}

bool FirewallRx3_is_empty(void) {
  return sb_queue_SW_RawEthernetMessage_1_is_empty(&FirewallRx3_recv_queue);
}

bool get_FirewallRx3_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data) {
  return sb_queue_SW_RawEthernetMessage_1_dequeue((sb_queue_SW_RawEthernetMessage_1_Recv_t *) &FirewallRx3_recv_queue, numDropped, data);
}

bool get_FirewallRx3(SW_RawEthernetMessage *data) {
  sb_event_counter_t numDropped;
  return get_FirewallRx3_poll (&numDropped, data);
}

void init(void) {
  sb_queue_SW_RawEthernetMessage_1_init((sb_queue_SW_RawEthernetMessage_1_t *) EthernetFramesTx0_queue_1);

  sb_queue_SW_RawEthernetMessage_1_init((sb_queue_SW_RawEthernetMessage_1_t *) EthernetFramesTx1_queue_1);

  sb_queue_SW_RawEthernetMessage_1_init((sb_queue_SW_RawEthernetMessage_1_t *) EthernetFramesTx2_queue_1);

  sb_queue_SW_RawEthernetMessage_1_init((sb_queue_SW_RawEthernetMessage_1_t *) EthernetFramesTx3_queue_1);

  sb_queue_SW_RawEthernetMessage_1_Recv_init(&MavlinkRx0_recv_queue, (sb_queue_SW_RawEthernetMessage_1_t *) MavlinkRx0_queue_1);

  sb_queue_SW_RawEthernetMessage_1_Recv_init(&MavlinkRx1_recv_queue, (sb_queue_SW_RawEthernetMessage_1_t *) MavlinkRx1_queue_1);

  sb_queue_SW_RawEthernetMessage_1_Recv_init(&MavlinkRx2_recv_queue, (sb_queue_SW_RawEthernetMessage_1_t *) MavlinkRx2_queue_1);

  sb_queue_SW_RawEthernetMessage_1_Recv_init(&MavlinkRx3_recv_queue, (sb_queue_SW_RawEthernetMessage_1_t *) MavlinkRx3_queue_1);

  sb_queue_SW_RawEthernetMessage_1_Recv_init(&FirewallRx0_recv_queue, (sb_queue_SW_RawEthernetMessage_1_t *) FirewallRx0_queue_1);

  sb_queue_SW_RawEthernetMessage_1_Recv_init(&FirewallRx1_recv_queue, (sb_queue_SW_RawEthernetMessage_1_t *) FirewallRx1_queue_1);

  sb_queue_SW_RawEthernetMessage_1_Recv_init(&FirewallRx2_recv_queue, (sb_queue_SW_RawEthernetMessage_1_t *) FirewallRx2_queue_1);

  sb_queue_SW_RawEthernetMessage_1_Recv_init(&FirewallRx3_recv_queue, (sb_queue_SW_RawEthernetMessage_1_t *) FirewallRx3_queue_1);

  seL4_ArduPilot_ArduPilot_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      seL4_ArduPilot_ArduPilot_timeTriggered();
      break;
    default:
      seL4_ArduPilot_ArduPilot_notify(channel);
  }
}
