// Do not edit this file as it will be overwritten if codegen is rerun

use data::*;

use proptest::prelude::*;

use super::test_apis::*;

use crate::bridge::seL4_TxFirewall_TxFirewall_GUMBOX as GUMBOX;

pub enum HarnessResult {
  RejectedPrecondition,
  FailedPostcondition(TestCaseError),
  Passed,
}

/** Contract-based test harness for the initialize entry point
  */
pub fn testInitializeCB() -> HarnessResult
{
  // [InvokeEntryPoint]: Invoke the entry point
  crate::seL4_TxFirewall_TxFirewall_initialize();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let api_EthernetFramesTxOut0 = get_EthernetFramesTxOut0();
  let api_EthernetFramesTxOut1 = get_EthernetFramesTxOut1();
  let api_EthernetFramesTxOut2 = get_EthernetFramesTxOut2();
  let api_EthernetFramesTxOut3 = get_EthernetFramesTxOut3();

  // [CheckPost]: invoke the oracle function
  if !GUMBOX::initialize_IEP_Post (api_EthernetFramesTxOut0, api_EthernetFramesTxOut1, api_EthernetFramesTxOut2, api_EthernetFramesTxOut3) {
    return HarnessResult::FailedPostcondition(
      TestCaseError::Fail("Postcondition failed: incorrect output behavior".into())
    );
  }

  return HarnessResult::Passed
}

#[macro_export]
macro_rules!
testInitializeCB_macro {
  (
    $test_name: ident,
    config: $config:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(empty in ::proptest::strategy::Just(())) {
        match $crate::test::util::cb_apis::testInitializeCB() {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            unreachable!("This branch is infeasible")
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}

/** Contract-based test harness for the compute entry point
  *
  * @param api_EthernetFramesTxIn0 incoming event data port
  * @param api_EthernetFramesTxIn1 incoming event data port
  * @param api_EthernetFramesTxIn2 incoming event data port
  * @param api_EthernetFramesTxIn3 incoming event data port
  */
pub fn testComputeCB(
  api_EthernetFramesTxIn0: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxIn1: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxIn2: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxIn3: Option<SW::RawEthernetMessage>) -> HarnessResult
{
  // Initialize the app
  crate::seL4_TxFirewall_TxFirewall_initialize();

  // [PutInPorts]: Set values on the input ports
  put_EthernetFramesTxIn0(api_EthernetFramesTxIn0);
  put_EthernetFramesTxIn1(api_EthernetFramesTxIn1);
  put_EthernetFramesTxIn2(api_EthernetFramesTxIn2);
  put_EthernetFramesTxIn3(api_EthernetFramesTxIn3);

  // [InvokeEntryPoint]: Invoke the entry point
  crate::seL4_TxFirewall_TxFirewall_timeTriggered();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let api_EthernetFramesTxOut0 = get_EthernetFramesTxOut0();
  let api_EthernetFramesTxOut1 = get_EthernetFramesTxOut1();
  let api_EthernetFramesTxOut2 = get_EthernetFramesTxOut2();
  let api_EthernetFramesTxOut3 = get_EthernetFramesTxOut3();

  // [CheckPost]: invoke the oracle function
  if !GUMBOX::compute_CEP_Post(api_EthernetFramesTxIn0, api_EthernetFramesTxIn1, api_EthernetFramesTxIn2, api_EthernetFramesTxIn3, api_EthernetFramesTxOut0, api_EthernetFramesTxOut1, api_EthernetFramesTxOut2, api_EthernetFramesTxOut3) {
    return HarnessResult::FailedPostcondition(TestCaseError::Fail("Postcondition failed: incorrect output behavior".into()));
  }

  return HarnessResult::Passed
}

/** Contract-based test harness for the compute entry point
  */
pub fn testComputeCB_container(container: PreStateContainer) -> HarnessResult
{
  return testComputeCB(container.api_EthernetFramesTxIn0, container.api_EthernetFramesTxIn1, container.api_EthernetFramesTxIn2, container.api_EthernetFramesTxIn3)
}

#[macro_export]
macro_rules!
testComputeCB_macro {
  (
    $test_name: ident,
    config: $config:expr,
    api_EthernetFramesTxIn0: $api_EthernetFramesTxIn0_strat:expr,
    api_EthernetFramesTxIn1: $api_EthernetFramesTxIn1_strat:expr,
    api_EthernetFramesTxIn2: $api_EthernetFramesTxIn2_strat:expr,
    api_EthernetFramesTxIn3: $api_EthernetFramesTxIn3_strat:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(
        (api_EthernetFramesTxIn0, api_EthernetFramesTxIn1, api_EthernetFramesTxIn2, api_EthernetFramesTxIn3)
            in ($api_EthernetFramesTxIn0_strat, $api_EthernetFramesTxIn1_strat, $api_EthernetFramesTxIn2_strat, $api_EthernetFramesTxIn3_strat)
      ) {
        match$crate::test::util::cb_apis::testComputeCB(api_EthernetFramesTxIn0, api_EthernetFramesTxIn1, api_EthernetFramesTxIn2, api_EthernetFramesTxIn3) {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            return Err(proptest::test_runner::TestCaseError::reject(
              "Precondition failed: invalid input combination",
            ))
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}
