// Do not edit this file as it will be overwritten if codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_EthernetFramesTxIn0: Option<SW::RawEthernetMessage>,
  pub api_EthernetFramesTxIn1: Option<SW::RawEthernetMessage>,
  pub api_EthernetFramesTxIn2: Option<SW::RawEthernetMessage>,
  pub api_EthernetFramesTxIn3: Option<SW::RawEthernetMessage>
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_EthernetFramesTxIn0(container.api_EthernetFramesTxIn0);
  put_EthernetFramesTxIn1(container.api_EthernetFramesTxIn1);
  put_EthernetFramesTxIn2(container.api_EthernetFramesTxIn2);
  put_EthernetFramesTxIn3(container.api_EthernetFramesTxIn3);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(
  EthernetFramesTxIn0: Option<SW::RawEthernetMessage>,
  EthernetFramesTxIn1: Option<SW::RawEthernetMessage>,
  EthernetFramesTxIn2: Option<SW::RawEthernetMessage>,
  EthernetFramesTxIn3: Option<SW::RawEthernetMessage>)
{
  put_EthernetFramesTxIn0(EthernetFramesTxIn0);
  put_EthernetFramesTxIn1(EthernetFramesTxIn1);
  put_EthernetFramesTxIn2(EthernetFramesTxIn2);
  put_EthernetFramesTxIn3(EthernetFramesTxIn3);
}

/// setter for IN EventDataPort
pub fn put_EthernetFramesTxIn0(value: Option<SW::RawEthernetMessage>)
{
  *extern_api::IN_EthernetFramesTxIn0.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// setter for IN EventDataPort
pub fn put_EthernetFramesTxIn1(value: Option<SW::RawEthernetMessage>)
{
  *extern_api::IN_EthernetFramesTxIn1.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// setter for IN EventDataPort
pub fn put_EthernetFramesTxIn2(value: Option<SW::RawEthernetMessage>)
{
  *extern_api::IN_EthernetFramesTxIn2.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// setter for IN EventDataPort
pub fn put_EthernetFramesTxIn3(value: Option<SW::RawEthernetMessage>)
{
  *extern_api::IN_EthernetFramesTxIn3.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// getter for OUT EventDataPort
pub fn get_EthernetFramesTxOut0() -> Option<SW::SizedEthernetMessage_Impl>
{
  return extern_api::OUT_EthernetFramesTxOut0.lock().unwrap_or_else(|e| e.into_inner()).clone()
}

/// getter for OUT EventDataPort
pub fn get_EthernetFramesTxOut1() -> Option<SW::SizedEthernetMessage_Impl>
{
  return extern_api::OUT_EthernetFramesTxOut1.lock().unwrap_or_else(|e| e.into_inner()).clone()
}

/// getter for OUT EventDataPort
pub fn get_EthernetFramesTxOut2() -> Option<SW::SizedEthernetMessage_Impl>
{
  return extern_api::OUT_EthernetFramesTxOut2.lock().unwrap_or_else(|e| e.into_inner()).clone()
}

/// getter for OUT EventDataPort
pub fn get_EthernetFramesTxOut3() -> Option<SW::SizedEthernetMessage_Impl>
{
  return extern_api::OUT_EthernetFramesTxOut3.lock().unwrap_or_else(|e| e.into_inner()).clone()
}
