// Do not edit this file as it will be overwritten if codegen is rerun

use data::*;

use proptest::prelude::*;

use super::test_apis::*;

use crate::bridge::seL4_MavlinkFirewall_MavlinkFirewall_GUMBOX as GUMBOX;

pub enum HarnessResult {
  RejectedPrecondition,
  FailedPostcondition(TestCaseError),
  Passed,
}

/** Contract-based test harness for the initialize entry point
  */
pub fn testInitializeCB() -> HarnessResult
{
  // [InvokeEntryPoint]: Invoke the entry point
  crate::seL4_MavlinkFirewall_MavlinkFirewall_initialize();

  return HarnessResult::Passed
}

#[macro_export]
macro_rules!
testInitializeCB_macro {
  (
    $test_name: ident,
    config: $config:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(empty in ::proptest::strategy::Just(())) {
        match $crate::test::util::cb_apis::testInitializeCB() {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            unreachable!("This branch is infeasible")
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}

/** Contract-based test harness for the compute entry point
  *
  * @param api_In0 incoming event data port
  * @param api_In1 incoming event data port
  * @param api_In2 incoming event data port
  * @param api_In3 incoming event data port
  */
pub fn testComputeCB(
  api_In0: Option<SW::UdpFrame_Impl>,
  api_In1: Option<SW::UdpFrame_Impl>,
  api_In2: Option<SW::UdpFrame_Impl>,
  api_In3: Option<SW::UdpFrame_Impl>) -> HarnessResult
{
  // Initialize the app
  crate::seL4_MavlinkFirewall_MavlinkFirewall_initialize();

  // [PutInPorts]: Set values on the input ports
  put_In0(api_In0);
  put_In1(api_In1);
  put_In2(api_In2);
  put_In3(api_In3);

  // [InvokeEntryPoint]: Invoke the entry point
  crate::seL4_MavlinkFirewall_MavlinkFirewall_timeTriggered();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let api_Out0 = get_Out0();
  let api_Out1 = get_Out1();
  let api_Out2 = get_Out2();
  let api_Out3 = get_Out3();

  // [CheckPost]: invoke the oracle function
  if !GUMBOX::compute_CEP_Post(api_In0, api_In1, api_In2, api_In3, api_Out0, api_Out1, api_Out2, api_Out3) {
    return HarnessResult::FailedPostcondition(TestCaseError::Fail("Postcondition failed: incorrect output behavior".into()));
  }

  return HarnessResult::Passed
}

/** Contract-based test harness for the compute entry point
  */
pub fn testComputeCB_container(container: PreStateContainer) -> HarnessResult
{
  return testComputeCB(container.api_In0, container.api_In1, container.api_In2, container.api_In3)
}

#[macro_export]
macro_rules!
testComputeCB_macro {
  (
    $test_name: ident,
    config: $config:expr,
    api_In0: $api_In0_strat:expr,
    api_In1: $api_In1_strat:expr,
    api_In2: $api_In2_strat:expr,
    api_In3: $api_In3_strat:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(
        (api_In0, api_In1, api_In2, api_In3)
            in ($api_In0_strat, $api_In1_strat, $api_In2_strat, $api_In3_strat)
      ) {
        match$crate::test::util::cb_apis::testComputeCB(api_In0, api_In1, api_In2, api_In3) {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            return Err(proptest::test_runner::TestCaseError::reject(
              "Precondition failed: invalid input combination",
            ))
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}
