// Do not edit this file as it will be overwritten if codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_In0: Option<SW::UdpFrame_Impl>,
  pub api_In1: Option<SW::UdpFrame_Impl>,
  pub api_In2: Option<SW::UdpFrame_Impl>,
  pub api_In3: Option<SW::UdpFrame_Impl>
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_In0(container.api_In0);
  put_In1(container.api_In1);
  put_In2(container.api_In2);
  put_In3(container.api_In3);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(
  In0: Option<SW::UdpFrame_Impl>,
  In1: Option<SW::UdpFrame_Impl>,
  In2: Option<SW::UdpFrame_Impl>,
  In3: Option<SW::UdpFrame_Impl>)
{
  put_In0(In0);
  put_In1(In1);
  put_In2(In2);
  put_In3(In3);
}

/// setter for IN EventDataPort
pub fn put_In0(value: Option<SW::UdpFrame_Impl>)
{
  *extern_api::IN_In0.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// setter for IN EventDataPort
pub fn put_In1(value: Option<SW::UdpFrame_Impl>)
{
  *extern_api::IN_In1.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// setter for IN EventDataPort
pub fn put_In2(value: Option<SW::UdpFrame_Impl>)
{
  *extern_api::IN_In2.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// setter for IN EventDataPort
pub fn put_In3(value: Option<SW::UdpFrame_Impl>)
{
  *extern_api::IN_In3.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// getter for OUT EventDataPort
pub fn get_Out0() -> Option<SW::RawEthernetMessage>
{
  return extern_api::OUT_Out0.lock().unwrap_or_else(|e| e.into_inner()).clone()
}

/// getter for OUT EventDataPort
pub fn get_Out1() -> Option<SW::RawEthernetMessage>
{
  return extern_api::OUT_Out1.lock().unwrap_or_else(|e| e.into_inner()).clone()
}

/// getter for OUT EventDataPort
pub fn get_Out2() -> Option<SW::RawEthernetMessage>
{
  return extern_api::OUT_Out2.lock().unwrap_or_else(|e| e.into_inner()).clone()
}

/// getter for OUT EventDataPort
pub fn get_Out3() -> Option<SW::RawEthernetMessage>
{
  return extern_api::OUT_Out3.lock().unwrap_or_else(|e| e.into_inner()).clone()
}
