// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {

  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct SizedEthernetMessage_Impl {
    pub amessage: RawEthernetMessage,
    pub sz: u16
  }

  impl Default for SizedEthernetMessage_Impl {
    fn default() -> Self
    {
      Self { amessage: [0; SW::SW_RawEthernetMessage_DIM_0], sz: 0 }
    }
  }

}