#pragma once

// Do not edit this file as it will be overwritten if codegen is rerun

#include <sb_aadl_types.h>
#include <sb_queue_SW_RawEthernetMessage_1.h>
#include <sb_queue_SW_RawEthernetMessage_1.h>
#include <sb_queue_SW_RawEthernetMessage_1.h>
#include <sb_queue_SW_RawEthernetMessage_1.h>
#include <sb_queue_SW_RawEthernetMessage_1.h>
#include <sb_queue_SW_RawEthernetMessage_1.h>
#include <sb_queue_SW_RawEthernetMessage_1.h>
#include <sb_queue_SW_RawEthernetMessage_1.h>
#include <sb_queue_SW_RawEthernetMessage_1.h>
#include <sb_queue_SW_RawEthernetMessage_1.h>
#include <sb_queue_SW_RawEthernetMessage_1.h>
#include <sb_queue_SW_RawEthernetMessage_1.h>
#include <sb_queue_SW_UdpFrame_Impl_1.h>
#include <sb_queue_SW_UdpFrame_Impl_1.h>
#include <sb_queue_SW_UdpFrame_Impl_1.h>
#include <sb_queue_SW_UdpFrame_Impl_1.h>
#include <sb_queue_SW_SizedEthernetMessage_Impl_1.h>
#include <sb_queue_SW_SizedEthernetMessage_Impl_1.h>
#include <sb_queue_SW_SizedEthernetMessage_Impl_1.h>
#include <sb_queue_SW_SizedEthernetMessage_Impl_1.h>
#include <sb_queue_SW_RawEthernetMessage_1.h>
#include <sb_queue_SW_RawEthernetMessage_1.h>
#include <sb_queue_SW_RawEthernetMessage_1.h>
#include <sb_queue_SW_RawEthernetMessage_1.h>
