#pragma once

#include <printf.h>
#include <util.h>
#include <stdint.h>
#include <microkit.h>
#include <sb_types.h>

// Do not edit this file as it will be overwritten if codegen is rerun


bool put_EthernetFramesTx0(const SW_RawEthernetMessage *data);
bool put_EthernetFramesTx1(const SW_RawEthernetMessage *data);
bool put_EthernetFramesTx2(const SW_RawEthernetMessage *data);
bool put_EthernetFramesTx3(const SW_RawEthernetMessage *data);
bool MavlinkRx0_is_empty(void);
bool get_MavlinkRx0_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data);
bool get_MavlinkRx0(SW_RawEthernetMessage *data);
bool MavlinkRx1_is_empty(void);
bool get_MavlinkRx1_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data);
bool get_MavlinkRx1(SW_RawEthernetMessage *data);
bool MavlinkRx2_is_empty(void);
bool get_MavlinkRx2_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data);
bool get_MavlinkRx2(SW_RawEthernetMessage *data);
bool MavlinkRx3_is_empty(void);
bool get_MavlinkRx3_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data);
bool get_MavlinkRx3(SW_RawEthernetMessage *data);
bool FirewallRx0_is_empty(void);
bool get_FirewallRx0_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data);
bool get_FirewallRx0(SW_RawEthernetMessage *data);
bool FirewallRx1_is_empty(void);
bool get_FirewallRx1_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data);
bool get_FirewallRx1(SW_RawEthernetMessage *data);
bool FirewallRx2_is_empty(void);
bool get_FirewallRx2_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data);
bool get_FirewallRx2(SW_RawEthernetMessage *data);
bool FirewallRx3_is_empty(void);
bool get_FirewallRx3_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data);
bool get_FirewallRx3(SW_RawEthernetMessage *data);
