// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

/** I-Guar: Integration constraint on TxFirewall's outgoing event data port EthernetFramesTxOut0
  *
  * guarantee valid_tx_out_message_port0
  *  Only valid ARP and IPV4 size messages transmitted by TxFirewall Port 0
  */
pub fn I_Guar_EthernetFramesTxOut0(EthernetFramesTxOut0: SW::SizedEthernetMessage_Impl) -> bool
{
  GumboLib::valid_arp(EthernetFramesTxOut0.amessage) & GumboLib::valid_output_arp_size(EthernetFramesTxOut0) |
    GumboLib::valid_ipv4(EthernetFramesTxOut0.amessage) & GumboLib::valid_output_ipv4_size(EthernetFramesTxOut0.amessage, EthernetFramesTxOut0)
}

/** I-Guar: Integration constraint on TxFirewall's outgoing event data port EthernetFramesTxOut0
  *
  * guarantee valid_tx_out_message_port0
  *  Only valid ARP and IPV4 size messages transmitted by TxFirewall Port 0
  */
pub fn I_Guar_Guard_EthernetFramesTxOut0(EthernetFramesTxOut0: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  implies!(
    EthernetFramesTxOut0.is_some(),
    I_Guar_EthernetFramesTxOut0(EthernetFramesTxOut0.unwrap())
  )
}

/** I-Guar: Integration constraint on TxFirewall's outgoing event data port EthernetFramesTxOut1
  *
  * guarantee valid_tx_out_message_port1
  *  Only valid ARP and IPV4 size messages transmitted by TxFirewall Port 1
  */
pub fn I_Guar_EthernetFramesTxOut1(EthernetFramesTxOut1: SW::SizedEthernetMessage_Impl) -> bool
{
  GumboLib::valid_arp(EthernetFramesTxOut1.amessage) & GumboLib::valid_output_arp_size(EthernetFramesTxOut1) |
    GumboLib::valid_ipv4(EthernetFramesTxOut1.amessage) & GumboLib::valid_output_ipv4_size(EthernetFramesTxOut1.amessage, EthernetFramesTxOut1)
}

/** I-Guar: Integration constraint on TxFirewall's outgoing event data port EthernetFramesTxOut1
  *
  * guarantee valid_tx_out_message_port1
  *  Only valid ARP and IPV4 size messages transmitted by TxFirewall Port 1
  */
pub fn I_Guar_Guard_EthernetFramesTxOut1(EthernetFramesTxOut1: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  implies!(
    EthernetFramesTxOut1.is_some(),
    I_Guar_EthernetFramesTxOut1(EthernetFramesTxOut1.unwrap())
  )
}

/** I-Guar: Integration constraint on TxFirewall's outgoing event data port EthernetFramesTxOut2
  *
  * guarantee valid_tx_out_message_port2
  *  Only valid ARP and IPV4 size messages transmitted by TxFirewall Port 2
  */
pub fn I_Guar_EthernetFramesTxOut2(EthernetFramesTxOut2: SW::SizedEthernetMessage_Impl) -> bool
{
  GumboLib::valid_arp(EthernetFramesTxOut2.amessage) & GumboLib::valid_output_arp_size(EthernetFramesTxOut2) |
    GumboLib::valid_ipv4(EthernetFramesTxOut2.amessage) & GumboLib::valid_output_ipv4_size(EthernetFramesTxOut2.amessage, EthernetFramesTxOut2)
}

/** I-Guar: Integration constraint on TxFirewall's outgoing event data port EthernetFramesTxOut2
  *
  * guarantee valid_tx_out_message_port2
  *  Only valid ARP and IPV4 size messages transmitted by TxFirewall Port 2
  */
pub fn I_Guar_Guard_EthernetFramesTxOut2(EthernetFramesTxOut2: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  implies!(
    EthernetFramesTxOut2.is_some(),
    I_Guar_EthernetFramesTxOut2(EthernetFramesTxOut2.unwrap())
  )
}

/** I-Guar: Integration constraint on TxFirewall's outgoing event data port EthernetFramesTxOut3
  *
  * guarantee valid_tx_out_message_port3
  *  Only valid ARP and IPV4 size messages transmitted by TxFirewall Port 3
  */
pub fn I_Guar_EthernetFramesTxOut3(EthernetFramesTxOut3: SW::SizedEthernetMessage_Impl) -> bool
{
  GumboLib::valid_arp(EthernetFramesTxOut3.amessage) & GumboLib::valid_output_arp_size(EthernetFramesTxOut3) |
    GumboLib::valid_ipv4(EthernetFramesTxOut3.amessage) & GumboLib::valid_output_ipv4_size(EthernetFramesTxOut3.amessage, EthernetFramesTxOut3)
}

/** I-Guar: Integration constraint on TxFirewall's outgoing event data port EthernetFramesTxOut3
  *
  * guarantee valid_tx_out_message_port3
  *  Only valid ARP and IPV4 size messages transmitted by TxFirewall Port 3
  */
pub fn I_Guar_Guard_EthernetFramesTxOut3(EthernetFramesTxOut3: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  implies!(
    EthernetFramesTxOut3.is_some(),
    I_Guar_EthernetFramesTxOut3(EthernetFramesTxOut3.unwrap())
  )
}

/** IEP-Post: Initialize Entrypoint Post-Condition
  *
  * @param api_EthernetFramesTxOut0 outgoing event data port
  * @param api_EthernetFramesTxOut1 outgoing event data port
  * @param api_EthernetFramesTxOut2 outgoing event data port
  * @param api_EthernetFramesTxOut3 outgoing event data port
  */
pub fn initialize_IEP_Post(
  api_EthernetFramesTxOut0: Option<SW::SizedEthernetMessage_Impl>,
  api_EthernetFramesTxOut1: Option<SW::SizedEthernetMessage_Impl>,
  api_EthernetFramesTxOut2: Option<SW::SizedEthernetMessage_Impl>,
  api_EthernetFramesTxOut3: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  // I-Guar-Guard: Integration constraints for TxFirewall's outgoing ports"
  I_Guar_Guard_EthernetFramesTxOut0(api_EthernetFramesTxOut0) &
  I_Guar_Guard_EthernetFramesTxOut1(api_EthernetFramesTxOut1) &
  I_Guar_Guard_EthernetFramesTxOut2(api_EthernetFramesTxOut2) &
  I_Guar_Guard_EthernetFramesTxOut3(api_EthernetFramesTxOut3)
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_07_tx0_can_send_valid_arp
  *   https://loonwerks.com/INSPECTA-Open-Platform/ardupilot-basic/requirements/Inspecta-HLRs.pdf#page=5
  * @param api_EthernetFramesTxIn0 incoming event data port
  * @param api_EthernetFramesTxOut0 outgoing event data port
  */
pub fn compute_spec_hlr_07_tx0_can_send_valid_arp_guarantee(
  api_EthernetFramesTxIn0: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxOut0: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  implies!(
    api_EthernetFramesTxIn0.is_some() && GumboLib::valid_arp(api_EthernetFramesTxIn0.unwrap()),
    api_EthernetFramesTxOut0.is_some() &&
      ((api_EthernetFramesTxIn0.unwrap() == api_EthernetFramesTxOut0.unwrap().amessage) &&
        GumboLib::valid_output_arp_size(api_EthernetFramesTxOut0.unwrap())))
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_12_tx0_can_send_valid_ipv4
  *   https://loonwerks.com/INSPECTA-Open-Platform/ardupilot-basic/requirements/Inspecta-HLRs.pdf#page=5
  * @param api_EthernetFramesTxIn0 incoming event data port
  * @param api_EthernetFramesTxOut0 outgoing event data port
  */
pub fn compute_spec_hlr_12_tx0_can_send_valid_ipv4_guarantee(
  api_EthernetFramesTxIn0: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxOut0: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  implies!(
    api_EthernetFramesTxIn0.is_some() && GumboLib::valid_ipv4(api_EthernetFramesTxIn0.unwrap()),
    api_EthernetFramesTxOut0.is_some() &&
      ((api_EthernetFramesTxIn0.unwrap() == api_EthernetFramesTxOut0.unwrap().amessage) &&
        GumboLib::valid_output_ipv4_size(api_EthernetFramesTxIn0.unwrap(), api_EthernetFramesTxOut0.unwrap())))
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_14_tx0_disallow
  *   https://loonwerks.com/INSPECTA-Open-Platform/ardupilot-basic/requirements/Inspecta-HLRs.pdf#page=6
  * @param api_EthernetFramesTxIn0 incoming event data port
  * @param api_EthernetFramesTxOut0 outgoing event data port
  */
pub fn compute_spec_hlr_14_tx0_disallow_guarantee(
  api_EthernetFramesTxIn0: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxOut0: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  implies!(
    api_EthernetFramesTxIn0.is_some() && !(GumboLib::tx_allow_outbound_frame(api_EthernetFramesTxIn0.unwrap())),
    api_EthernetFramesTxOut0.is_none())
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_16_tx0_no_input
  *   https://loonwerks.com/INSPECTA-Open-Platform/ardupilot-basic/requirements/Inspecta-HLRs.pdf#page=6
  * @param api_EthernetFramesTxIn0 incoming event data port
  * @param api_EthernetFramesTxOut0 outgoing event data port
  */
pub fn compute_spec_hlr_16_tx0_no_input_guarantee(
  api_EthernetFramesTxIn0: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxOut0: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  api_EthernetFramesTxIn0.is_some() | api_EthernetFramesTxOut0.is_none()
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_07_tx1_can_send_valid_arp
  *   https://loonwerks.com/INSPECTA-Open-Platform/ardupilot-basic/requirements/Inspecta-HLRs.pdf#page=5
  * @param api_EthernetFramesTxIn1 incoming event data port
  * @param api_EthernetFramesTxOut1 outgoing event data port
  */
pub fn compute_spec_hlr_07_tx1_can_send_valid_arp_guarantee(
  api_EthernetFramesTxIn1: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxOut1: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  implies!(
    api_EthernetFramesTxIn1.is_some() && GumboLib::valid_arp(api_EthernetFramesTxIn1.unwrap()),
    api_EthernetFramesTxOut1.is_some() &&
      ((api_EthernetFramesTxIn1.unwrap() == api_EthernetFramesTxOut1.unwrap().amessage) &&
        GumboLib::valid_output_arp_size(api_EthernetFramesTxOut1.unwrap())))
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_12_tx1_can_send_valid_ipv4
  *   https://loonwerks.com/INSPECTA-Open-Platform/ardupilot-basic/requirements/Inspecta-HLRs.pdf#page=5
  * @param api_EthernetFramesTxIn1 incoming event data port
  * @param api_EthernetFramesTxOut1 outgoing event data port
  */
pub fn compute_spec_hlr_12_tx1_can_send_valid_ipv4_guarantee(
  api_EthernetFramesTxIn1: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxOut1: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  implies!(
    api_EthernetFramesTxIn1.is_some() && GumboLib::valid_ipv4(api_EthernetFramesTxIn1.unwrap()),
    api_EthernetFramesTxOut1.is_some() &&
      ((api_EthernetFramesTxIn1.unwrap() == api_EthernetFramesTxOut1.unwrap().amessage) &&
        GumboLib::valid_output_ipv4_size(api_EthernetFramesTxIn1.unwrap(), api_EthernetFramesTxOut1.unwrap())))
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_14_tx1_disallow
  *   https://loonwerks.com/INSPECTA-Open-Platform/ardupilot-basic/requirements/Inspecta-HLRs.pdf#page=6
  * @param api_EthernetFramesTxIn1 incoming event data port
  * @param api_EthernetFramesTxOut1 outgoing event data port
  */
pub fn compute_spec_hlr_14_tx1_disallow_guarantee(
  api_EthernetFramesTxIn1: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxOut1: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  implies!(
    api_EthernetFramesTxIn1.is_some() && !(GumboLib::tx_allow_outbound_frame(api_EthernetFramesTxIn1.unwrap())),
    api_EthernetFramesTxOut1.is_none())
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_16_tx1_no_input
  *   https://loonwerks.com/INSPECTA-Open-Platform/ardupilot-basic/requirements/Inspecta-HLRs.pdf#page=6
  * @param api_EthernetFramesTxIn1 incoming event data port
  * @param api_EthernetFramesTxOut1 outgoing event data port
  */
pub fn compute_spec_hlr_16_tx1_no_input_guarantee(
  api_EthernetFramesTxIn1: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxOut1: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  api_EthernetFramesTxIn1.is_some() | api_EthernetFramesTxOut1.is_none()
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_07_tx2_can_send_valid_arp
  *   https://loonwerks.com/INSPECTA-Open-Platform/ardupilot-basic/requirements/Inspecta-HLRs.pdf#page=5
  * @param api_EthernetFramesTxIn2 incoming event data port
  * @param api_EthernetFramesTxOut2 outgoing event data port
  */
pub fn compute_spec_hlr_07_tx2_can_send_valid_arp_guarantee(
  api_EthernetFramesTxIn2: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxOut2: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  implies!(
    api_EthernetFramesTxIn2.is_some() && GumboLib::valid_arp(api_EthernetFramesTxIn2.unwrap()),
    api_EthernetFramesTxOut2.is_some() &&
      ((api_EthernetFramesTxIn2.unwrap() == api_EthernetFramesTxOut2.unwrap().amessage) &&
        GumboLib::valid_output_arp_size(api_EthernetFramesTxOut2.unwrap())))
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_12_tx2_can_send_valid_ipv4
  *   https://loonwerks.com/INSPECTA-Open-Platform/ardupilot-basic/requirements/Inspecta-HLRs.pdf#page=5
  * @param api_EthernetFramesTxIn2 incoming event data port
  * @param api_EthernetFramesTxOut2 outgoing event data port
  */
pub fn compute_spec_hlr_12_tx2_can_send_valid_ipv4_guarantee(
  api_EthernetFramesTxIn2: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxOut2: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  implies!(
    api_EthernetFramesTxIn2.is_some() && GumboLib::valid_ipv4(api_EthernetFramesTxIn2.unwrap()),
    api_EthernetFramesTxOut2.is_some() &&
      ((api_EthernetFramesTxIn2.unwrap() == api_EthernetFramesTxOut2.unwrap().amessage) &&
        GumboLib::valid_output_ipv4_size(api_EthernetFramesTxIn2.unwrap(), api_EthernetFramesTxOut2.unwrap())))
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_14_tx2_disallow
  *   https://loonwerks.com/INSPECTA-Open-Platform/ardupilot-basic/requirements/Inspecta-HLRs.pdf#page=6
  * @param api_EthernetFramesTxIn2 incoming event data port
  * @param api_EthernetFramesTxOut2 outgoing event data port
  */
pub fn compute_spec_hlr_14_tx2_disallow_guarantee(
  api_EthernetFramesTxIn2: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxOut2: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  implies!(
    api_EthernetFramesTxIn2.is_some() && !(GumboLib::tx_allow_outbound_frame(api_EthernetFramesTxIn2.unwrap())),
    api_EthernetFramesTxOut2.is_none())
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_16_tx2_no_input
  *   https://loonwerks.com/INSPECTA-Open-Platform/ardupilot-basic/requirements/Inspecta-HLRs.pdf#page=6
  * @param api_EthernetFramesTxIn2 incoming event data port
  * @param api_EthernetFramesTxOut2 outgoing event data port
  */
pub fn compute_spec_hlr_16_tx2_no_input_guarantee(
  api_EthernetFramesTxIn2: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxOut2: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  api_EthernetFramesTxIn2.is_some() | api_EthernetFramesTxOut2.is_none()
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_07_tx3_can_send_valid_arp
  *   https://loonwerks.com/INSPECTA-Open-Platform/ardupilot-basic/requirements/Inspecta-HLRs.pdf#page=5
  * @param api_EthernetFramesTxIn3 incoming event data port
  * @param api_EthernetFramesTxOut3 outgoing event data port
  */
pub fn compute_spec_hlr_07_tx3_can_send_valid_arp_guarantee(
  api_EthernetFramesTxIn3: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxOut3: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  implies!(
    api_EthernetFramesTxIn3.is_some() && GumboLib::valid_arp(api_EthernetFramesTxIn3.unwrap()),
    api_EthernetFramesTxOut3.is_some() &&
      ((api_EthernetFramesTxIn3.unwrap() == api_EthernetFramesTxOut3.unwrap().amessage) &&
        GumboLib::valid_output_arp_size(api_EthernetFramesTxOut3.unwrap())))
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_12_tx3_can_send_valid_ipv4
  *   https://loonwerks.com/INSPECTA-Open-Platform/ardupilot-basic/requirements/Inspecta-HLRs.pdf#page=5
  * @param api_EthernetFramesTxIn3 incoming event data port
  * @param api_EthernetFramesTxOut3 outgoing event data port
  */
pub fn compute_spec_hlr_12_tx3_can_send_valid_ipv4_guarantee(
  api_EthernetFramesTxIn3: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxOut3: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  implies!(
    api_EthernetFramesTxIn3.is_some() && GumboLib::valid_ipv4(api_EthernetFramesTxIn3.unwrap()),
    api_EthernetFramesTxOut3.is_some() &&
      ((api_EthernetFramesTxIn3.unwrap() == api_EthernetFramesTxOut3.unwrap().amessage) &&
        GumboLib::valid_output_ipv4_size(api_EthernetFramesTxIn3.unwrap(), api_EthernetFramesTxOut3.unwrap())))
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_14_tx3_disallow
  *   https://loonwerks.com/INSPECTA-Open-Platform/ardupilot-basic/requirements/Inspecta-HLRs.pdf#page=6
  * @param api_EthernetFramesTxIn3 incoming event data port
  * @param api_EthernetFramesTxOut3 outgoing event data port
  */
pub fn compute_spec_hlr_14_tx3_disallow_guarantee(
  api_EthernetFramesTxIn3: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxOut3: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  implies!(
    api_EthernetFramesTxIn3.is_some() && !(GumboLib::tx_allow_outbound_frame(api_EthernetFramesTxIn3.unwrap())),
    api_EthernetFramesTxOut3.is_none())
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_16_tx3_no_input
  *   https://loonwerks.com/INSPECTA-Open-Platform/ardupilot-basic/requirements/Inspecta-HLRs.pdf#page=6
  * @param api_EthernetFramesTxIn3 incoming event data port
  * @param api_EthernetFramesTxOut3 outgoing event data port
  */
pub fn compute_spec_hlr_16_tx3_no_input_guarantee(
  api_EthernetFramesTxIn3: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxOut3: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  api_EthernetFramesTxIn3.is_some() | api_EthernetFramesTxOut3.is_none()
}

/** CEP-T-Guar: Top-level guarantee contracts for TxFirewall's compute entrypoint
  *
  * @param api_EthernetFramesTxIn0 incoming event data port
  * @param api_EthernetFramesTxIn1 incoming event data port
  * @param api_EthernetFramesTxIn2 incoming event data port
  * @param api_EthernetFramesTxIn3 incoming event data port
  * @param api_EthernetFramesTxOut0 outgoing event data port
  * @param api_EthernetFramesTxOut1 outgoing event data port
  * @param api_EthernetFramesTxOut2 outgoing event data port
  * @param api_EthernetFramesTxOut3 outgoing event data port
  */
pub fn compute_CEP_T_Guar(
  api_EthernetFramesTxIn0: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxIn1: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxIn2: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxIn3: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxOut0: Option<SW::SizedEthernetMessage_Impl>,
  api_EthernetFramesTxOut1: Option<SW::SizedEthernetMessage_Impl>,
  api_EthernetFramesTxOut2: Option<SW::SizedEthernetMessage_Impl>,
  api_EthernetFramesTxOut3: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  let r0: bool = compute_spec_hlr_07_tx0_can_send_valid_arp_guarantee(api_EthernetFramesTxIn0, api_EthernetFramesTxOut0);
  let r1: bool = compute_spec_hlr_12_tx0_can_send_valid_ipv4_guarantee(api_EthernetFramesTxIn0, api_EthernetFramesTxOut0);
  let r2: bool = compute_spec_hlr_14_tx0_disallow_guarantee(api_EthernetFramesTxIn0, api_EthernetFramesTxOut0);
  let r3: bool = compute_spec_hlr_16_tx0_no_input_guarantee(api_EthernetFramesTxIn0, api_EthernetFramesTxOut0);
  let r4: bool = compute_spec_hlr_07_tx1_can_send_valid_arp_guarantee(api_EthernetFramesTxIn1, api_EthernetFramesTxOut1);
  let r5: bool = compute_spec_hlr_12_tx1_can_send_valid_ipv4_guarantee(api_EthernetFramesTxIn1, api_EthernetFramesTxOut1);
  let r6: bool = compute_spec_hlr_14_tx1_disallow_guarantee(api_EthernetFramesTxIn1, api_EthernetFramesTxOut1);
  let r7: bool = compute_spec_hlr_16_tx1_no_input_guarantee(api_EthernetFramesTxIn1, api_EthernetFramesTxOut1);
  let r8: bool = compute_spec_hlr_07_tx2_can_send_valid_arp_guarantee(api_EthernetFramesTxIn2, api_EthernetFramesTxOut2);
  let r9: bool = compute_spec_hlr_12_tx2_can_send_valid_ipv4_guarantee(api_EthernetFramesTxIn2, api_EthernetFramesTxOut2);
  let r10: bool = compute_spec_hlr_14_tx2_disallow_guarantee(api_EthernetFramesTxIn2, api_EthernetFramesTxOut2);
  let r11: bool = compute_spec_hlr_16_tx2_no_input_guarantee(api_EthernetFramesTxIn2, api_EthernetFramesTxOut2);
  let r12: bool = compute_spec_hlr_07_tx3_can_send_valid_arp_guarantee(api_EthernetFramesTxIn3, api_EthernetFramesTxOut3);
  let r13: bool = compute_spec_hlr_12_tx3_can_send_valid_ipv4_guarantee(api_EthernetFramesTxIn3, api_EthernetFramesTxOut3);
  let r14: bool = compute_spec_hlr_14_tx3_disallow_guarantee(api_EthernetFramesTxIn3, api_EthernetFramesTxOut3);
  let r15: bool = compute_spec_hlr_16_tx3_no_input_guarantee(api_EthernetFramesTxIn3, api_EthernetFramesTxOut3);

  return r0 && r1 && r2 && r3 && r4 && r5 && r6 && r7 && r8 && r9 && r10 && r11 && r12 && r13 && r14 && r15;
}

/** CEP-Post: Compute Entrypoint Post-Condition for TxFirewall
  *
  * @param api_EthernetFramesTxIn0 incoming event data port
  * @param api_EthernetFramesTxIn1 incoming event data port
  * @param api_EthernetFramesTxIn2 incoming event data port
  * @param api_EthernetFramesTxIn3 incoming event data port
  * @param api_EthernetFramesTxOut0 outgoing event data port
  * @param api_EthernetFramesTxOut1 outgoing event data port
  * @param api_EthernetFramesTxOut2 outgoing event data port
  * @param api_EthernetFramesTxOut3 outgoing event data port
  */
pub fn compute_CEP_Post(
  api_EthernetFramesTxIn0: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxIn1: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxIn2: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxIn3: Option<SW::RawEthernetMessage>,
  api_EthernetFramesTxOut0: Option<SW::SizedEthernetMessage_Impl>,
  api_EthernetFramesTxOut1: Option<SW::SizedEthernetMessage_Impl>,
  api_EthernetFramesTxOut2: Option<SW::SizedEthernetMessage_Impl>,
  api_EthernetFramesTxOut3: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  // I-Guar-Guard: Integration constraints for TxFirewall's outgoing ports
  let r0: bool = I_Guar_Guard_EthernetFramesTxOut0(api_EthernetFramesTxOut0);
  let r1: bool = I_Guar_Guard_EthernetFramesTxOut1(api_EthernetFramesTxOut1);
  let r2: bool = I_Guar_Guard_EthernetFramesTxOut2(api_EthernetFramesTxOut2);
  let r3: bool = I_Guar_Guard_EthernetFramesTxOut3(api_EthernetFramesTxOut3);

  // CEP-Guar: guarantee clauses of TxFirewall's compute entrypoint
  let r4: bool = compute_CEP_T_Guar(api_EthernetFramesTxIn0, api_EthernetFramesTxIn1, api_EthernetFramesTxIn2, api_EthernetFramesTxIn3, api_EthernetFramesTxOut0, api_EthernetFramesTxOut1, api_EthernetFramesTxOut2, api_EthernetFramesTxOut3);

  return r0 && r1 && r2 && r3 && r4;
}
