#include "seL4_LowLevelEthernetDriver_LowLevelEthernetDriver.h"

// Do not edit this file as it will be overwritten if codegen is rerun

void seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_initialize(void);
void seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_notify(microkit_channel channel);
void seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_timeTriggered(void);

volatile sb_queue_SW_SizedEthernetMessage_Impl_1_t *EthernetFramesTx0_queue_1;
sb_queue_SW_SizedEthernetMessage_Impl_1_Recv_t EthernetFramesTx0_recv_queue;
volatile sb_queue_SW_SizedEthernetMessage_Impl_1_t *EthernetFramesTx1_queue_1;
sb_queue_SW_SizedEthernetMessage_Impl_1_Recv_t EthernetFramesTx1_recv_queue;
volatile sb_queue_SW_SizedEthernetMessage_Impl_1_t *EthernetFramesTx2_queue_1;
sb_queue_SW_SizedEthernetMessage_Impl_1_Recv_t EthernetFramesTx2_recv_queue;
volatile sb_queue_SW_SizedEthernetMessage_Impl_1_t *EthernetFramesTx3_queue_1;
sb_queue_SW_SizedEthernetMessage_Impl_1_Recv_t EthernetFramesTx3_recv_queue;
volatile sb_queue_SW_RawEthernetMessage_1_t *EthernetFramesRx0_queue_1;
volatile sb_queue_SW_RawEthernetMessage_1_t *EthernetFramesRx1_queue_1;
volatile sb_queue_SW_RawEthernetMessage_1_t *EthernetFramesRx2_queue_1;
volatile sb_queue_SW_RawEthernetMessage_1_t *EthernetFramesRx3_queue_1;

#define PORT_FROM_MON 52

bool EthernetFramesTx0_is_empty(void) {
  return sb_queue_SW_SizedEthernetMessage_Impl_1_is_empty(&EthernetFramesTx0_recv_queue);
}

bool get_EthernetFramesTx0_poll(sb_event_counter_t *numDropped, SW_SizedEthernetMessage_Impl *data) {
  return sb_queue_SW_SizedEthernetMessage_Impl_1_dequeue((sb_queue_SW_SizedEthernetMessage_Impl_1_Recv_t *) &EthernetFramesTx0_recv_queue, numDropped, data);
}

bool get_EthernetFramesTx0(SW_SizedEthernetMessage_Impl *data) {
  sb_event_counter_t numDropped;
  return get_EthernetFramesTx0_poll (&numDropped, data);
}

bool EthernetFramesTx1_is_empty(void) {
  return sb_queue_SW_SizedEthernetMessage_Impl_1_is_empty(&EthernetFramesTx1_recv_queue);
}

bool get_EthernetFramesTx1_poll(sb_event_counter_t *numDropped, SW_SizedEthernetMessage_Impl *data) {
  return sb_queue_SW_SizedEthernetMessage_Impl_1_dequeue((sb_queue_SW_SizedEthernetMessage_Impl_1_Recv_t *) &EthernetFramesTx1_recv_queue, numDropped, data);
}

bool get_EthernetFramesTx1(SW_SizedEthernetMessage_Impl *data) {
  sb_event_counter_t numDropped;
  return get_EthernetFramesTx1_poll (&numDropped, data);
}

bool EthernetFramesTx2_is_empty(void) {
  return sb_queue_SW_SizedEthernetMessage_Impl_1_is_empty(&EthernetFramesTx2_recv_queue);
}

bool get_EthernetFramesTx2_poll(sb_event_counter_t *numDropped, SW_SizedEthernetMessage_Impl *data) {
  return sb_queue_SW_SizedEthernetMessage_Impl_1_dequeue((sb_queue_SW_SizedEthernetMessage_Impl_1_Recv_t *) &EthernetFramesTx2_recv_queue, numDropped, data);
}

bool get_EthernetFramesTx2(SW_SizedEthernetMessage_Impl *data) {
  sb_event_counter_t numDropped;
  return get_EthernetFramesTx2_poll (&numDropped, data);
}

bool EthernetFramesTx3_is_empty(void) {
  return sb_queue_SW_SizedEthernetMessage_Impl_1_is_empty(&EthernetFramesTx3_recv_queue);
}

bool get_EthernetFramesTx3_poll(sb_event_counter_t *numDropped, SW_SizedEthernetMessage_Impl *data) {
  return sb_queue_SW_SizedEthernetMessage_Impl_1_dequeue((sb_queue_SW_SizedEthernetMessage_Impl_1_Recv_t *) &EthernetFramesTx3_recv_queue, numDropped, data);
}

bool get_EthernetFramesTx3(SW_SizedEthernetMessage_Impl *data) {
  sb_event_counter_t numDropped;
  return get_EthernetFramesTx3_poll (&numDropped, data);
}

bool put_EthernetFramesRx0(const SW_RawEthernetMessage *data) {
  sb_queue_SW_RawEthernetMessage_1_enqueue((sb_queue_SW_RawEthernetMessage_1_t *) EthernetFramesRx0_queue_1, (SW_RawEthernetMessage *) data);

  return true;
}

bool put_EthernetFramesRx1(const SW_RawEthernetMessage *data) {
  sb_queue_SW_RawEthernetMessage_1_enqueue((sb_queue_SW_RawEthernetMessage_1_t *) EthernetFramesRx1_queue_1, (SW_RawEthernetMessage *) data);

  return true;
}

bool put_EthernetFramesRx2(const SW_RawEthernetMessage *data) {
  sb_queue_SW_RawEthernetMessage_1_enqueue((sb_queue_SW_RawEthernetMessage_1_t *) EthernetFramesRx2_queue_1, (SW_RawEthernetMessage *) data);

  return true;
}

bool put_EthernetFramesRx3(const SW_RawEthernetMessage *data) {
  sb_queue_SW_RawEthernetMessage_1_enqueue((sb_queue_SW_RawEthernetMessage_1_t *) EthernetFramesRx3_queue_1, (SW_RawEthernetMessage *) data);

  return true;
}

void init(void) {
  sb_queue_SW_SizedEthernetMessage_Impl_1_Recv_init(&EthernetFramesTx0_recv_queue, (sb_queue_SW_SizedEthernetMessage_Impl_1_t *) EthernetFramesTx0_queue_1);

  sb_queue_SW_SizedEthernetMessage_Impl_1_Recv_init(&EthernetFramesTx1_recv_queue, (sb_queue_SW_SizedEthernetMessage_Impl_1_t *) EthernetFramesTx1_queue_1);

  sb_queue_SW_SizedEthernetMessage_Impl_1_Recv_init(&EthernetFramesTx2_recv_queue, (sb_queue_SW_SizedEthernetMessage_Impl_1_t *) EthernetFramesTx2_queue_1);

  sb_queue_SW_SizedEthernetMessage_Impl_1_Recv_init(&EthernetFramesTx3_recv_queue, (sb_queue_SW_SizedEthernetMessage_Impl_1_t *) EthernetFramesTx3_queue_1);

  sb_queue_SW_RawEthernetMessage_1_init((sb_queue_SW_RawEthernetMessage_1_t *) EthernetFramesRx0_queue_1);

  sb_queue_SW_RawEthernetMessage_1_init((sb_queue_SW_RawEthernetMessage_1_t *) EthernetFramesRx1_queue_1);

  sb_queue_SW_RawEthernetMessage_1_init((sb_queue_SW_RawEthernetMessage_1_t *) EthernetFramesRx2_queue_1);

  sb_queue_SW_RawEthernetMessage_1_init((sb_queue_SW_RawEthernetMessage_1_t *) EthernetFramesRx3_queue_1);

  seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_timeTriggered();
      break;
    default:
      seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_notify(channel);
  }
}
