#include "seL4_MavlinkFirewall_MavlinkFirewall.h"

// Do not edit this file as it will be overwritten if codegen is rerun

void seL4_MavlinkFirewall_MavlinkFirewall_initialize(void);
void seL4_MavlinkFirewall_MavlinkFirewall_notify(microkit_channel channel);
void seL4_MavlinkFirewall_MavlinkFirewall_timeTriggered(void);

volatile sb_queue_SW_RawEthernetMessage_1_t *Out0_queue_1;
volatile sb_queue_SW_RawEthernetMessage_1_t *Out1_queue_1;
volatile sb_queue_SW_RawEthernetMessage_1_t *Out2_queue_1;
volatile sb_queue_SW_RawEthernetMessage_1_t *Out3_queue_1;
volatile sb_queue_SW_UdpFrame_Impl_1_t *In0_queue_1;
sb_queue_SW_UdpFrame_Impl_1_Recv_t In0_recv_queue;
volatile sb_queue_SW_UdpFrame_Impl_1_t *In1_queue_1;
sb_queue_SW_UdpFrame_Impl_1_Recv_t In1_recv_queue;
volatile sb_queue_SW_UdpFrame_Impl_1_t *In2_queue_1;
sb_queue_SW_UdpFrame_Impl_1_Recv_t In2_recv_queue;
volatile sb_queue_SW_UdpFrame_Impl_1_t *In3_queue_1;
sb_queue_SW_UdpFrame_Impl_1_Recv_t In3_recv_queue;

#define PORT_FROM_MON 58

bool put_Out0(const SW_RawEthernetMessage *data) {
  sb_queue_SW_RawEthernetMessage_1_enqueue((sb_queue_SW_RawEthernetMessage_1_t *) Out0_queue_1, (SW_RawEthernetMessage *) data);

  return true;
}

bool put_Out1(const SW_RawEthernetMessage *data) {
  sb_queue_SW_RawEthernetMessage_1_enqueue((sb_queue_SW_RawEthernetMessage_1_t *) Out1_queue_1, (SW_RawEthernetMessage *) data);

  return true;
}

bool put_Out2(const SW_RawEthernetMessage *data) {
  sb_queue_SW_RawEthernetMessage_1_enqueue((sb_queue_SW_RawEthernetMessage_1_t *) Out2_queue_1, (SW_RawEthernetMessage *) data);

  return true;
}

bool put_Out3(const SW_RawEthernetMessage *data) {
  sb_queue_SW_RawEthernetMessage_1_enqueue((sb_queue_SW_RawEthernetMessage_1_t *) Out3_queue_1, (SW_RawEthernetMessage *) data);

  return true;
}

bool In0_is_empty(void) {
  return sb_queue_SW_UdpFrame_Impl_1_is_empty(&In0_recv_queue);
}

bool get_In0_poll(sb_event_counter_t *numDropped, SW_UdpFrame_Impl *data) {
  return sb_queue_SW_UdpFrame_Impl_1_dequeue((sb_queue_SW_UdpFrame_Impl_1_Recv_t *) &In0_recv_queue, numDropped, data);
}

bool get_In0(SW_UdpFrame_Impl *data) {
  sb_event_counter_t numDropped;
  return get_In0_poll (&numDropped, data);
}

bool In1_is_empty(void) {
  return sb_queue_SW_UdpFrame_Impl_1_is_empty(&In1_recv_queue);
}

bool get_In1_poll(sb_event_counter_t *numDropped, SW_UdpFrame_Impl *data) {
  return sb_queue_SW_UdpFrame_Impl_1_dequeue((sb_queue_SW_UdpFrame_Impl_1_Recv_t *) &In1_recv_queue, numDropped, data);
}

bool get_In1(SW_UdpFrame_Impl *data) {
  sb_event_counter_t numDropped;
  return get_In1_poll (&numDropped, data);
}

bool In2_is_empty(void) {
  return sb_queue_SW_UdpFrame_Impl_1_is_empty(&In2_recv_queue);
}

bool get_In2_poll(sb_event_counter_t *numDropped, SW_UdpFrame_Impl *data) {
  return sb_queue_SW_UdpFrame_Impl_1_dequeue((sb_queue_SW_UdpFrame_Impl_1_Recv_t *) &In2_recv_queue, numDropped, data);
}

bool get_In2(SW_UdpFrame_Impl *data) {
  sb_event_counter_t numDropped;
  return get_In2_poll (&numDropped, data);
}

bool In3_is_empty(void) {
  return sb_queue_SW_UdpFrame_Impl_1_is_empty(&In3_recv_queue);
}

bool get_In3_poll(sb_event_counter_t *numDropped, SW_UdpFrame_Impl *data) {
  return sb_queue_SW_UdpFrame_Impl_1_dequeue((sb_queue_SW_UdpFrame_Impl_1_Recv_t *) &In3_recv_queue, numDropped, data);
}

bool get_In3(SW_UdpFrame_Impl *data) {
  sb_event_counter_t numDropped;
  return get_In3_poll (&numDropped, data);
}

void init(void) {
  sb_queue_SW_RawEthernetMessage_1_init((sb_queue_SW_RawEthernetMessage_1_t *) Out0_queue_1);

  sb_queue_SW_RawEthernetMessage_1_init((sb_queue_SW_RawEthernetMessage_1_t *) Out1_queue_1);

  sb_queue_SW_RawEthernetMessage_1_init((sb_queue_SW_RawEthernetMessage_1_t *) Out2_queue_1);

  sb_queue_SW_RawEthernetMessage_1_init((sb_queue_SW_RawEthernetMessage_1_t *) Out3_queue_1);

  sb_queue_SW_UdpFrame_Impl_1_Recv_init(&In0_recv_queue, (sb_queue_SW_UdpFrame_Impl_1_t *) In0_queue_1);

  sb_queue_SW_UdpFrame_Impl_1_Recv_init(&In1_recv_queue, (sb_queue_SW_UdpFrame_Impl_1_t *) In1_queue_1);

  sb_queue_SW_UdpFrame_Impl_1_Recv_init(&In2_recv_queue, (sb_queue_SW_UdpFrame_Impl_1_t *) In2_queue_1);

  sb_queue_SW_UdpFrame_Impl_1_Recv_init(&In3_recv_queue, (sb_queue_SW_UdpFrame_Impl_1_t *) In3_queue_1);

  seL4_MavlinkFirewall_MavlinkFirewall_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      seL4_MavlinkFirewall_MavlinkFirewall_timeTriggered();
      break;
    default:
      seL4_MavlinkFirewall_MavlinkFirewall_notify(channel);
  }
}
