// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

use proptest::prelude::*;

pub fn option_strategy_default
  <T: Clone + std::fmt::Debug, 
   S:  Strategy<Value = T>> (base: S) -> impl Strategy<Value = Option<T>>
{
  option_strategy_bias(1, base)
}

pub fn option_strategy_bias
  <T: Clone + std::fmt::Debug, 
   S:  Strategy<Value = T>> (
  bias: u32,
  base: S) -> impl Strategy<Value = Option<T>>
{
  prop_oneof![
    bias => base.prop_map(Some),
    1 => Just(None),
  ]
}

pub fn SW_RawEthernetMessage_strategy_default() -> impl Strategy<Value = SW::RawEthernetMessage>
{
  SW_RawEthernetMessage_strategy_cust(any::<u8>())
}

pub fn SW_RawEthernetMessage_strategy_cust<u8_strategy: Strategy<Value = u8>> (base_strategy: u8_strategy) -> impl Strategy<Value = SW::RawEthernetMessage>
{
  proptest::collection::vec(base_strategy, SW::SW_RawEthernetMessage_DIM_0)
    .prop_map(|v| {
      let boxed: Box<[u8; SW::SW_RawEthernetMessage_DIM_0]> = v.into_boxed_slice().try_into().unwrap();
      *boxed
  })
}

pub fn SW_EthIpUdpHeaders_strategy_default() -> impl Strategy<Value = SW::EthIpUdpHeaders>
{
  SW_EthIpUdpHeaders_strategy_cust(any::<u8>())
}

pub fn SW_EthIpUdpHeaders_strategy_cust<u8_strategy: Strategy<Value = u8>> (base_strategy: u8_strategy) -> impl Strategy<Value = SW::EthIpUdpHeaders>
{
  proptest::collection::vec(base_strategy, SW::SW_EthIpUdpHeaders_DIM_0)
    .prop_map(|v| {
      let boxed: Box<[u8; SW::SW_EthIpUdpHeaders_DIM_0]> = v.into_boxed_slice().try_into().unwrap();
      *boxed
  })
}

pub fn SW_UdpPayload_strategy_default() -> impl Strategy<Value = SW::UdpPayload>
{
  SW_UdpPayload_strategy_cust(any::<u8>())
}

pub fn SW_UdpPayload_strategy_cust<u8_strategy: Strategy<Value = u8>> (base_strategy: u8_strategy) -> impl Strategy<Value = SW::UdpPayload>
{
  proptest::collection::vec(base_strategy, SW::SW_UdpPayload_DIM_0)
    .prop_map(|v| {
      let boxed: Box<[u8; SW::SW_UdpPayload_DIM_0]> = v.into_boxed_slice().try_into().unwrap();
      *boxed
  })
}

pub fn SW_u16Array_strategy_default() -> impl Strategy<Value = SW::u16Array>
{
  SW_u16Array_strategy_cust(any::<u16>())
}

pub fn SW_u16Array_strategy_cust<u16_strategy: Strategy<Value = u16>> (base_strategy: u16_strategy) -> impl Strategy<Value = SW::u16Array>
{
  proptest::collection::vec(base_strategy, SW::SW_u16Array_DIM_0)
    .prop_map(|v| {
      let boxed: Box<[u16; SW::SW_u16Array_DIM_0]> = v.into_boxed_slice().try_into().unwrap();
      *boxed
  })
}

pub fn SW_SizedEthernetMessage_Impl_strategy_default() -> impl Strategy<Value = SW::SizedEthernetMessage_Impl>
{
  SW_SizedEthernetMessage_Impl_strategy_cust(
    SW_RawEthernetMessage_strategy_default(),
    any::<u16>()
  )
}

pub fn SW_SizedEthernetMessage_Impl_strategy_cust
  <amessage_SW_RawEthernetMessage_strategy: Strategy<Value = SW::RawEthernetMessage>, 
   sz_u16_strategy: Strategy<Value = u16>> (
  amessage_strategy: amessage_SW_RawEthernetMessage_strategy,
  sz_strategy: sz_u16_strategy) -> impl Strategy<Value = SW::SizedEthernetMessage_Impl>
{
  (amessage_strategy, sz_strategy).prop_map(|(amessage, sz)| {
    SW::SizedEthernetMessage_Impl { amessage, sz }
  })
}

pub fn SW_UdpFrame_Impl_strategy_default() -> impl Strategy<Value = SW::UdpFrame_Impl>
{
  SW_UdpFrame_Impl_strategy_cust(
    SW_EthIpUdpHeaders_strategy_default(),
    SW_UdpPayload_strategy_default()
  )
}

pub fn SW_UdpFrame_Impl_strategy_cust
  <headers_SW_EthIpUdpHeaders_strategy: Strategy<Value = SW::EthIpUdpHeaders>, 
   payload_SW_UdpPayload_strategy: Strategy<Value = SW::UdpPayload>> (
  headers_strategy: headers_SW_EthIpUdpHeaders_strategy,
  payload_strategy: payload_SW_UdpPayload_strategy) -> impl Strategy<Value = SW::UdpFrame_Impl>
{
  (headers_strategy, payload_strategy).prop_map(|(headers, payload)| {
    SW::UdpFrame_Impl { headers, payload }
  })
}
