#include <stdint.h>
#include <microkit.h>

#define PORT_TO_SEL4_ARDUPILOT_ARDUPILOT_MON 61
#define PORT_TO_SEL4_MAVLINKFIREWALL_MAVLINKFIREWALL_MON 59
#define PORT_TO_SEL4_RXFIREWALL_RXFIREWALL_MON 57
#define PORT_TO_SEL4_TXFIREWALL_TXFIREWALL_MON 55
#define PORT_TO_SEL4_LOWLEVELETHERNETDRIVER_LOWLEVELETHERNETDRIVER_MON 53

void init(void) {}

void notified(microkit_channel channel) {
  switch(channel) {
    case PORT_TO_SEL4_ARDUPILOT_ARDUPILOT_MON:
      microkit_notify(PORT_TO_SEL4_ARDUPILOT_ARDUPILOT_MON);
      break;
    case PORT_TO_SEL4_MAVLINKFIREWALL_MAVLINKFIREWALL_MON:
      microkit_notify(PORT_TO_SEL4_MAVLINKFIREWALL_MAVLINKFIREWALL_MON);
      break;
    case PORT_TO_SEL4_RXFIREWALL_RXFIREWALL_MON:
      microkit_notify(PORT_TO_SEL4_RXFIREWALL_RXFIREWALL_MON);
      break;
    case PORT_TO_SEL4_TXFIREWALL_TXFIREWALL_MON:
      microkit_notify(PORT_TO_SEL4_TXFIREWALL_TXFIREWALL_MON);
      break;
    case PORT_TO_SEL4_LOWLEVELETHERNETDRIVER_LOWLEVELETHERNETDRIVER_MON:
      microkit_notify(PORT_TO_SEL4_LOWLEVELETHERNETDRIVER_LOWLEVELETHERNETDRIVER_MON);
      break;
  }
}
