# Do not edit this file as it will be overwritten if codegen is rerun

MICROKIT_TOOL ?= $(MICROKIT_SDK)/bin/microkit

CFLAGS := -mcpu=$(CPU) \
	-mstrict-align \
	-ffreestanding \
	-nostdlib \
	-g3 \
	-O3 \
	-Wall -Wno-unused-function -Werror -Wno-unused-command-line-argument \
	-I$(MICROKIT_BOARD_DIR)/include \
	-target $(TARGET)

LDFLAGS := -L$(MICROKIT_BOARD_DIR)/lib
LIBS := --start-group -lmicrokit -Tmicrokit.ld --end-group

SYSTEM_FILE := $(TOP_DIR)/microkit.system
SCHEDULE_FILE := $(TOP_DIR)/microkit.schedule.xml

IMAGES := seL4_ArduPilot_ArduPilot.elf seL4_ArduPilot_ArduPilot_MON.elf seL4_MavlinkFirewall_MavlinkFirewall.elf seL4_MavlinkFirewall_MavlinkFirewall_MON.elf seL4_RxFirewall_RxFirewall.elf seL4_RxFirewall_RxFirewall_MON.elf seL4_TxFirewall_TxFirewall.elf seL4_TxFirewall_TxFirewall_MON.elf seL4_LowLevelEthernetDriver_LowLevelEthernetDriver.elf seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_MON.elf pacer.elf
IMAGE_FILE = loader.img
REPORT_FILE = report.txt

UTIL_OBJS = printf.o util.o

TYPES_DIR = $(TOP_DIR)/types
TYPE_OBJS := $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_UdpFrame_Impl_1.o $(TOP_DIR)/build/sb_queue_SW_UdpFrame_Impl_1.o $(TOP_DIR)/build/sb_queue_SW_UdpFrame_Impl_1.o $(TOP_DIR)/build/sb_queue_SW_UdpFrame_Impl_1.o $(TOP_DIR)/build/sb_queue_SW_SizedEthernetMessage_Impl_1.o $(TOP_DIR)/build/sb_queue_SW_SizedEthernetMessage_Impl_1.o $(TOP_DIR)/build/sb_queue_SW_SizedEthernetMessage_Impl_1.o $(TOP_DIR)/build/sb_queue_SW_SizedEthernetMessage_Impl_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o

# exporting TOP_TYPES_INCLUDE in case other makefiles need it
export TOP_TYPES_INCLUDE = -I$(TYPES_DIR)/include

TOP_INCLUDE = $(TOP_TYPES_INCLUDE) -I$(TOP_DIR)/util/include

all: $(IMAGE_FILE)
	CHECK_FLAGS_BOARD_MD5:=.board_cflags-$(shell echo -- ${CFLAGS} ${MICROKIT_BOARD} ${MICROKIT_CONFIG}| shasum | sed 's/ *-//')

${CHECK_FLAGS_BOARD_MD5}:
	-rm -f .board_cflags-*
	touch $@

%.o: ${TOP_DIR}/util/src/%.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ -I$(TOP_DIR)/util/include

$(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o: $(TOP_DIR)/types/src/sb_queue_SW_RawEthernetMessage_1.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE)


$(TOP_DIR)/build/sb_queue_SW_UdpFrame_Impl_1.o: $(TOP_DIR)/types/src/sb_queue_SW_UdpFrame_Impl_1.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE)


$(TOP_DIR)/build/sb_queue_SW_SizedEthernetMessage_Impl_1.o: $(TOP_DIR)/types/src/sb_queue_SW_SizedEthernetMessage_Impl_1.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE)


# monitor
seL4_ArduPilot_ArduPilot_MON.o: $(TOP_DIR)/components/seL4_ArduPilot_ArduPilot/src/seL4_ArduPilot_ArduPilot_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/seL4_ArduPilot_ArduPilot/include

# user code
seL4_ArduPilot_ArduPilot_user.o: $(TOP_DIR)/components/seL4_ArduPilot_ArduPilot/src/seL4_ArduPilot_ArduPilot_user.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE)/ -I$(TOP_DIR)/components/seL4_ArduPilot_ArduPilot/include

seL4_ArduPilot_ArduPilot.o: $(TOP_DIR)/components/seL4_ArduPilot_ArduPilot/src/seL4_ArduPilot_ArduPilot.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/seL4_ArduPilot_ArduPilot/include

# monitor
seL4_MavlinkFirewall_MavlinkFirewall_MON.o: $(TOP_DIR)/components/seL4_MavlinkFirewall_MavlinkFirewall/src/seL4_MavlinkFirewall_MavlinkFirewall_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/seL4_MavlinkFirewall_MavlinkFirewall/include

# user code
seL4_MavlinkFirewall_MavlinkFirewall_rust:
	make -C ${CRATES_DIR}/seL4_MavlinkFirewall_MavlinkFirewall $(RUST_MAKE_TARGET)

seL4_MavlinkFirewall_MavlinkFirewall.o: $(TOP_DIR)/components/seL4_MavlinkFirewall_MavlinkFirewall/src/seL4_MavlinkFirewall_MavlinkFirewall.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/seL4_MavlinkFirewall_MavlinkFirewall/include

# monitor
seL4_RxFirewall_RxFirewall_MON.o: $(TOP_DIR)/components/seL4_RxFirewall_RxFirewall/src/seL4_RxFirewall_RxFirewall_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/seL4_RxFirewall_RxFirewall/include

# user code
seL4_RxFirewall_RxFirewall_rust:
	make -C ${CRATES_DIR}/seL4_RxFirewall_RxFirewall $(RUST_MAKE_TARGET)

seL4_RxFirewall_RxFirewall.o: $(TOP_DIR)/components/seL4_RxFirewall_RxFirewall/src/seL4_RxFirewall_RxFirewall.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/seL4_RxFirewall_RxFirewall/include

# monitor
seL4_TxFirewall_TxFirewall_MON.o: $(TOP_DIR)/components/seL4_TxFirewall_TxFirewall/src/seL4_TxFirewall_TxFirewall_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/seL4_TxFirewall_TxFirewall/include

# user code
seL4_TxFirewall_TxFirewall_rust:
	make -C ${CRATES_DIR}/seL4_TxFirewall_TxFirewall $(RUST_MAKE_TARGET)

seL4_TxFirewall_TxFirewall.o: $(TOP_DIR)/components/seL4_TxFirewall_TxFirewall/src/seL4_TxFirewall_TxFirewall.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/seL4_TxFirewall_TxFirewall/include

# monitor
seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_MON.o: $(TOP_DIR)/components/seL4_LowLevelEthernetDriver_LowLevelEthernetDriver/src/seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/seL4_LowLevelEthernetDriver_LowLevelEthernetDriver/include

# user code
seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_rust:
	make -C ${CRATES_DIR}/seL4_LowLevelEthernetDriver_LowLevelEthernetDriver $(RUST_MAKE_TARGET)

seL4_LowLevelEthernetDriver_LowLevelEthernetDriver.o: $(TOP_DIR)/components/seL4_LowLevelEthernetDriver_LowLevelEthernetDriver/src/seL4_LowLevelEthernetDriver_LowLevelEthernetDriver.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/seL4_LowLevelEthernetDriver_LowLevelEthernetDriver/include

pacer.o: $(TOP_DIR)/components/pacer/src/pacer.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ -I$(TOP_INCLUDE)

seL4_ArduPilot_ArduPilot_MON.elf: seL4_ArduPilot_ArduPilot_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

seL4_ArduPilot_ArduPilot.elf: $(UTIL_OBJS) $(TYPE_OBJS) seL4_ArduPilot_ArduPilot_user.o seL4_ArduPilot_ArduPilot.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

seL4_MavlinkFirewall_MavlinkFirewall_MON.elf: seL4_MavlinkFirewall_MavlinkFirewall_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

seL4_MavlinkFirewall_MavlinkFirewall.elf: $(UTIL_OBJS) $(TYPE_OBJS) seL4_MavlinkFirewall_MavlinkFirewall_rust seL4_MavlinkFirewall_MavlinkFirewall.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/seL4_MavlinkFirewall_MavlinkFirewall/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lseL4_MavlinkFirewall_MavlinkFirewall -o $@

seL4_RxFirewall_RxFirewall_MON.elf: seL4_RxFirewall_RxFirewall_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

seL4_RxFirewall_RxFirewall.elf: $(UTIL_OBJS) $(TYPE_OBJS) seL4_RxFirewall_RxFirewall_rust seL4_RxFirewall_RxFirewall.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/seL4_RxFirewall_RxFirewall/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lseL4_RxFirewall_RxFirewall -o $@

seL4_TxFirewall_TxFirewall_MON.elf: seL4_TxFirewall_TxFirewall_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

seL4_TxFirewall_TxFirewall.elf: $(UTIL_OBJS) $(TYPE_OBJS) seL4_TxFirewall_TxFirewall_rust seL4_TxFirewall_TxFirewall.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/seL4_TxFirewall_TxFirewall/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lseL4_TxFirewall_TxFirewall -o $@

seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_MON.elf: seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

seL4_LowLevelEthernetDriver_LowLevelEthernetDriver.elf: $(UTIL_OBJS) $(TYPE_OBJS) seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_rust seL4_LowLevelEthernetDriver_LowLevelEthernetDriver.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/seL4_LowLevelEthernetDriver_LowLevelEthernetDriver/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lseL4_LowLevelEthernetDriver_LowLevelEthernetDriver -o $@

pacer.elf: $(UTIL_OBJS) $(TYPE_OBJS) pacer.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

$(IMAGE_FILE): $(IMAGES) $(SYSTEM_FILE)
	xmllint --xinclude $(SYSTEM_FILE) -o $(SYSTEM_FILE).merged
	$(MICROKIT_TOOL) $(SYSTEM_FILE).merged --search-path $(TOP_BUILD_DIR) --board $(MICROKIT_BOARD) --config $(MICROKIT_CONFIG) -o $(IMAGE_FILE) -r $(REPORT_FILE)


qemu: $(IMAGE_FILE)
	$(QEMU) -machine virt,virtualization=on \
			-cpu cortex-a53 \
			-serial mon:stdio \
			-device loader,file=$(IMAGE_FILE),addr=0x70000000,cpu-num=0 \
			-m size=2G \
			-nographic

clean::
	rm -f *.o

test:: 
	make -C ${CRATES_DIR}/seL4_MavlinkFirewall_MavlinkFirewall test
	make -C ${CRATES_DIR}/seL4_RxFirewall_RxFirewall test
	make -C ${CRATES_DIR}/seL4_TxFirewall_TxFirewall test
	make -C ${CRATES_DIR}/seL4_LowLevelEthernetDriver_LowLevelEthernetDriver test

clean:: 
	make -C ${CRATES_DIR}/seL4_MavlinkFirewall_MavlinkFirewall clean
	make -C ${CRATES_DIR}/seL4_RxFirewall_RxFirewall clean
	make -C ${CRATES_DIR}/seL4_TxFirewall_TxFirewall clean
	make -C ${CRATES_DIR}/seL4_LowLevelEthernetDriver_LowLevelEthernetDriver clean

verus: 
	make -C ${CRATES_DIR}/seL4_MavlinkFirewall_MavlinkFirewall verus
	make -C ${CRATES_DIR}/seL4_RxFirewall_RxFirewall verus
	make -C ${CRATES_DIR}/seL4_TxFirewall_TxFirewall verus
	make -C ${CRATES_DIR}/seL4_LowLevelEthernetDriver_LowLevelEthernetDriver verus
