// Do not edit this file as it will be overwritten if codegen is rerun

use data::*;

use proptest::prelude::*;

use super::test_apis::*;

use crate::bridge::seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_GUMBOX as GUMBOX;

pub enum HarnessResult {
  RejectedPrecondition,
  FailedPostcondition(TestCaseError),
  Passed,
}

/** Contract-based test harness for the initialize entry point
  */
pub fn testInitializeCB() -> HarnessResult
{
  // [InvokeEntryPoint]: Invoke the entry point
  crate::seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_initialize();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let api_EthernetFramesRx0 = get_EthernetFramesRx0();
  let api_EthernetFramesRx1 = get_EthernetFramesRx1();
  let api_EthernetFramesRx2 = get_EthernetFramesRx2();
  let api_EthernetFramesRx3 = get_EthernetFramesRx3();

  // [CheckPost]: invoke the oracle function
  if !GUMBOX::initialize_IEP_Post (api_EthernetFramesRx0, api_EthernetFramesRx1, api_EthernetFramesRx2, api_EthernetFramesRx3) {
    return HarnessResult::FailedPostcondition(
      TestCaseError::Fail("Postcondition failed: incorrect output behavior".into())
    );
  }

  return HarnessResult::Passed
}

#[macro_export]
macro_rules!
testInitializeCB_macro {
  (
    $test_name: ident,
    config: $config:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(empty in ::proptest::strategy::Just(())) {
        match $crate::test::util::cb_apis::testInitializeCB() {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            unreachable!("This branch is infeasible")
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}

/** Contract-based test harness for the compute entry point
  *
  * @param api_EthernetFramesTx0 incoming event data port
  * @param api_EthernetFramesTx1 incoming event data port
  * @param api_EthernetFramesTx2 incoming event data port
  * @param api_EthernetFramesTx3 incoming event data port
  */
pub fn testComputeCB(
  api_EthernetFramesTx0: Option<SW::SizedEthernetMessage_Impl>,
  api_EthernetFramesTx1: Option<SW::SizedEthernetMessage_Impl>,
  api_EthernetFramesTx2: Option<SW::SizedEthernetMessage_Impl>,
  api_EthernetFramesTx3: Option<SW::SizedEthernetMessage_Impl>) -> HarnessResult
{
  // Initialize the app
  crate::seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_initialize();

  // [CheckPre]: check/filter based on pre-condition.
  if !GUMBOX::compute_CEP_Pre (api_EthernetFramesTx0, api_EthernetFramesTx1, api_EthernetFramesTx2, api_EthernetFramesTx3) {
    return HarnessResult::RejectedPrecondition;
  }

  // [PutInPorts]: Set values on the input ports
  put_EthernetFramesTx0(api_EthernetFramesTx0);
  put_EthernetFramesTx1(api_EthernetFramesTx1);
  put_EthernetFramesTx2(api_EthernetFramesTx2);
  put_EthernetFramesTx3(api_EthernetFramesTx3);

  // [InvokeEntryPoint]: Invoke the entry point
  crate::seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_timeTriggered();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let api_EthernetFramesRx0 = get_EthernetFramesRx0();
  let api_EthernetFramesRx1 = get_EthernetFramesRx1();
  let api_EthernetFramesRx2 = get_EthernetFramesRx2();
  let api_EthernetFramesRx3 = get_EthernetFramesRx3();

  // [CheckPost]: invoke the oracle function
  if !GUMBOX::compute_CEP_Post(api_EthernetFramesTx0, api_EthernetFramesTx1, api_EthernetFramesTx2, api_EthernetFramesTx3, api_EthernetFramesRx0, api_EthernetFramesRx1, api_EthernetFramesRx2, api_EthernetFramesRx3) {
    return HarnessResult::FailedPostcondition(TestCaseError::Fail("Postcondition failed: incorrect output behavior".into()));
  }

  return HarnessResult::Passed
}

/** Contract-based test harness for the compute entry point
  */
pub fn testComputeCB_container(container: PreStateContainer) -> HarnessResult
{
  return testComputeCB(container.api_EthernetFramesTx0, container.api_EthernetFramesTx1, container.api_EthernetFramesTx2, container.api_EthernetFramesTx3)
}

#[macro_export]
macro_rules!
testComputeCB_macro {
  (
    $test_name: ident,
    config: $config:expr,
    api_EthernetFramesTx0: $api_EthernetFramesTx0_strat:expr,
    api_EthernetFramesTx1: $api_EthernetFramesTx1_strat:expr,
    api_EthernetFramesTx2: $api_EthernetFramesTx2_strat:expr,
    api_EthernetFramesTx3: $api_EthernetFramesTx3_strat:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(
        (api_EthernetFramesTx0, api_EthernetFramesTx1, api_EthernetFramesTx2, api_EthernetFramesTx3)
            in ($api_EthernetFramesTx0_strat, $api_EthernetFramesTx1_strat, $api_EthernetFramesTx2_strat, $api_EthernetFramesTx3_strat)
      ) {
        match$crate::test::util::cb_apis::testComputeCB(api_EthernetFramesTx0, api_EthernetFramesTx1, api_EthernetFramesTx2, api_EthernetFramesTx3) {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            return Err(proptest::test_runner::TestCaseError::reject(
              "Precondition failed: invalid input combination",
            ))
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}
