// Do not edit this file as it will be overwritten if codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_EthernetFramesTx0: Option<SW::SizedEthernetMessage_Impl>,
  pub api_EthernetFramesTx1: Option<SW::SizedEthernetMessage_Impl>,
  pub api_EthernetFramesTx2: Option<SW::SizedEthernetMessage_Impl>,
  pub api_EthernetFramesTx3: Option<SW::SizedEthernetMessage_Impl>
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_EthernetFramesTx0(container.api_EthernetFramesTx0);
  put_EthernetFramesTx1(container.api_EthernetFramesTx1);
  put_EthernetFramesTx2(container.api_EthernetFramesTx2);
  put_EthernetFramesTx3(container.api_EthernetFramesTx3);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(
  EthernetFramesTx0: Option<SW::SizedEthernetMessage_Impl>,
  EthernetFramesTx1: Option<SW::SizedEthernetMessage_Impl>,
  EthernetFramesTx2: Option<SW::SizedEthernetMessage_Impl>,
  EthernetFramesTx3: Option<SW::SizedEthernetMessage_Impl>)
{
  put_EthernetFramesTx0(EthernetFramesTx0);
  put_EthernetFramesTx1(EthernetFramesTx1);
  put_EthernetFramesTx2(EthernetFramesTx2);
  put_EthernetFramesTx3(EthernetFramesTx3);
}

/// getter for OUT EventDataPort
pub fn get_EthernetFramesRx0() -> Option<SW::RawEthernetMessage>
{
  return extern_api::OUT_EthernetFramesRx0.lock().unwrap_or_else(|e| e.into_inner()).clone()
}

/// getter for OUT EventDataPort
pub fn get_EthernetFramesRx1() -> Option<SW::RawEthernetMessage>
{
  return extern_api::OUT_EthernetFramesRx1.lock().unwrap_or_else(|e| e.into_inner()).clone()
}

/// getter for OUT EventDataPort
pub fn get_EthernetFramesRx2() -> Option<SW::RawEthernetMessage>
{
  return extern_api::OUT_EthernetFramesRx2.lock().unwrap_or_else(|e| e.into_inner()).clone()
}

/// getter for OUT EventDataPort
pub fn get_EthernetFramesRx3() -> Option<SW::RawEthernetMessage>
{
  return extern_api::OUT_EthernetFramesRx3.lock().unwrap_or_else(|e| e.into_inner()).clone()
}

/// setter for IN EventDataPort
pub fn put_EthernetFramesTx0(value: Option<SW::SizedEthernetMessage_Impl>)
{
  *extern_api::IN_EthernetFramesTx0.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// setter for IN EventDataPort
pub fn put_EthernetFramesTx1(value: Option<SW::SizedEthernetMessage_Impl>)
{
  *extern_api::IN_EthernetFramesTx1.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// setter for IN EventDataPort
pub fn put_EthernetFramesTx2(value: Option<SW::SizedEthernetMessage_Impl>)
{
  *extern_api::IN_EthernetFramesTx2.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// setter for IN EventDataPort
pub fn put_EthernetFramesTx3(value: Option<SW::SizedEthernetMessage_Impl>)
{
  *extern_api::IN_EthernetFramesTx3.lock().unwrap_or_else(|e| e.into_inner()) = value
}
