// Do not edit this file as it will be overwritten if codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

/** I-Assm: Integration constraint on RxFirewall's incoming event data port EthernetFramesRxIn0
  *
  * assume valid_message_port0
  *   Only valid messages being sent to the RxFirewall Port 0
  */
pub fn I_Assm_EthernetFramesRxIn0(EthernetFramesRxIn0: SW::RawEthernetMessage) -> bool
{
  GumboLib::valid_arp(EthernetFramesRxIn0) ||
    (GumboLib::valid_ipv4_udp_mavlink(EthernetFramesRxIn0) ||
      (GumboLib::valid_ipv4_udp_port(EthernetFramesRxIn0) || !(GumboLib::rx_allow_outbound_frame(EthernetFramesRxIn0))))
}

/** I-Assm: Integration constraint on RxFirewall's incoming event data port EthernetFramesRxIn0
  *
  * assume valid_message_port0
  *   Only valid messages being sent to the RxFirewall Port 0
  */
pub fn I_Assm_Guard_EthernetFramesRxIn0(EthernetFramesRxIn0: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    EthernetFramesRxIn0.is_some(),
    I_Assm_EthernetFramesRxIn0(EthernetFramesRxIn0.unwrap())
  )
}

/** I-Assm: Integration constraint on RxFirewall's incoming event data port EthernetFramesRxIn1
  *
  * assume valid_message_port1
  *   Only valid messages being sent to the RxFirewall Port 1
  */
pub fn I_Assm_EthernetFramesRxIn1(EthernetFramesRxIn1: SW::RawEthernetMessage) -> bool
{
  GumboLib::valid_arp(EthernetFramesRxIn1) ||
    (GumboLib::valid_ipv4_udp_mavlink(EthernetFramesRxIn1) ||
      (GumboLib::valid_ipv4_udp_port(EthernetFramesRxIn1) || !(GumboLib::rx_allow_outbound_frame(EthernetFramesRxIn1))))
}

/** I-Assm: Integration constraint on RxFirewall's incoming event data port EthernetFramesRxIn1
  *
  * assume valid_message_port1
  *   Only valid messages being sent to the RxFirewall Port 1
  */
pub fn I_Assm_Guard_EthernetFramesRxIn1(EthernetFramesRxIn1: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    EthernetFramesRxIn1.is_some(),
    I_Assm_EthernetFramesRxIn1(EthernetFramesRxIn1.unwrap())
  )
}

/** I-Assm: Integration constraint on RxFirewall's incoming event data port EthernetFramesRxIn2
  *
  * assume valid_message_port2
  *   Only valid messages being sent to the RxFirewall Port 2
  */
pub fn I_Assm_EthernetFramesRxIn2(EthernetFramesRxIn2: SW::RawEthernetMessage) -> bool
{
  GumboLib::valid_arp(EthernetFramesRxIn2) ||
    (GumboLib::valid_ipv4_udp_mavlink(EthernetFramesRxIn2) ||
      (GumboLib::valid_ipv4_udp_port(EthernetFramesRxIn2) || !(GumboLib::rx_allow_outbound_frame(EthernetFramesRxIn2))))
}

/** I-Assm: Integration constraint on RxFirewall's incoming event data port EthernetFramesRxIn2
  *
  * assume valid_message_port2
  *   Only valid messages being sent to the RxFirewall Port 2
  */
pub fn I_Assm_Guard_EthernetFramesRxIn2(EthernetFramesRxIn2: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    EthernetFramesRxIn2.is_some(),
    I_Assm_EthernetFramesRxIn2(EthernetFramesRxIn2.unwrap())
  )
}

/** I-Assm: Integration constraint on RxFirewall's incoming event data port EthernetFramesRxIn3
  *
  * assume valid_message_port3
  *   Only valid messages being sent to the RxFirewall Port 3
  */
pub fn I_Assm_EthernetFramesRxIn3(EthernetFramesRxIn3: SW::RawEthernetMessage) -> bool
{
  GumboLib::valid_arp(EthernetFramesRxIn3) ||
    (GumboLib::valid_ipv4_udp_mavlink(EthernetFramesRxIn3) ||
      (GumboLib::valid_ipv4_udp_port(EthernetFramesRxIn3) || !(GumboLib::rx_allow_outbound_frame(EthernetFramesRxIn3))))
}

/** I-Assm: Integration constraint on RxFirewall's incoming event data port EthernetFramesRxIn3
  *
  * assume valid_message_port3
  *   Only valid messages being sent to the RxFirewall Port 3
  */
pub fn I_Assm_Guard_EthernetFramesRxIn3(EthernetFramesRxIn3: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    EthernetFramesRxIn3.is_some(),
    I_Assm_EthernetFramesRxIn3(EthernetFramesRxIn3.unwrap())
  )
}

/** CEP-Pre: Compute Entrypoint Pre-Condition for RxFirewall
  *
  * @param api_EthernetFramesRxIn0 incoming event data port
  * @param api_EthernetFramesRxIn1 incoming event data port
  * @param api_EthernetFramesRxIn2 incoming event data port
  * @param api_EthernetFramesRxIn3 incoming event data port
  */
pub fn compute_CEP_Pre(
  api_EthernetFramesRxIn0: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRxIn1: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRxIn2: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRxIn3: Option<SW::RawEthernetMessage>) -> bool
{
  // I-Assm-Guard: Integration constraints for RxFirewall's incoming ports
  let r0: bool = I_Assm_Guard_EthernetFramesRxIn0(api_EthernetFramesRxIn0);
  let r1: bool = I_Assm_Guard_EthernetFramesRxIn1(api_EthernetFramesRxIn1);
  let r2: bool = I_Assm_Guard_EthernetFramesRxIn2(api_EthernetFramesRxIn2);
  let r3: bool = I_Assm_Guard_EthernetFramesRxIn3(api_EthernetFramesRxIn3);

  return r0 && r1 && r2 && r3;
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_05_rx0_can_send_arp_to_vmm
  * @param api_EthernetFramesRxIn0 incoming event data port
  * @param api_MavlinkOut0 outgoing event data port
  * @param api_VmmOut0 outgoing event data port
  */
pub fn compute_spec_hlr_05_rx0_can_send_arp_to_vmm_guarantee(
  api_EthernetFramesRxIn0: Option<SW::RawEthernetMessage>,
  api_MavlinkOut0: Option<SW::UdpFrame_Impl>,
  api_VmmOut0: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    api_EthernetFramesRxIn0.is_some() && GumboLib::valid_arp(api_EthernetFramesRxIn0.unwrap()),
    api_VmmOut0.is_some() &&
      ((api_EthernetFramesRxIn0.unwrap() == api_VmmOut0.unwrap()) &&
        api_MavlinkOut0.is_none()))
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_18_rx0_can_send_mavlink_udp
  * @param api_EthernetFramesRxIn0 incoming event data port
  * @param api_MavlinkOut0 outgoing event data port
  * @param api_VmmOut0 outgoing event data port
  */
pub fn compute_spec_hlr_18_rx0_can_send_mavlink_udp_guarantee(
  api_EthernetFramesRxIn0: Option<SW::RawEthernetMessage>,
  api_MavlinkOut0: Option<SW::UdpFrame_Impl>,
  api_VmmOut0: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    api_EthernetFramesRxIn0.is_some() && GumboLib::valid_ipv4_udp_mavlink(api_EthernetFramesRxIn0.unwrap()),
    api_MavlinkOut0.is_some() &&
      (GumboLib::input_eq_mav_output(api_EthernetFramesRxIn0.unwrap(), api_MavlinkOut0.unwrap()) && api_VmmOut0.is_none()))
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_13_rx0_can_send_ipv4_udp
  * @param api_EthernetFramesRxIn0 incoming event data port
  * @param api_MavlinkOut0 outgoing event data port
  * @param api_VmmOut0 outgoing event data port
  */
pub fn compute_spec_hlr_13_rx0_can_send_ipv4_udp_guarantee(
  api_EthernetFramesRxIn0: Option<SW::RawEthernetMessage>,
  api_MavlinkOut0: Option<SW::UdpFrame_Impl>,
  api_VmmOut0: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    api_EthernetFramesRxIn0.is_some() && GumboLib::valid_ipv4_udp_port(api_EthernetFramesRxIn0.unwrap()),
    api_VmmOut0.is_some() &&
      ((api_EthernetFramesRxIn0.unwrap() == api_VmmOut0.unwrap()) &&
        api_MavlinkOut0.is_none()))
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_15_rx0_disallow
  * @param api_EthernetFramesRxIn0 incoming event data port
  * @param api_MavlinkOut0 outgoing event data port
  * @param api_VmmOut0 outgoing event data port
  */
pub fn compute_spec_hlr_15_rx0_disallow_guarantee(
  api_EthernetFramesRxIn0: Option<SW::RawEthernetMessage>,
  api_MavlinkOut0: Option<SW::UdpFrame_Impl>,
  api_VmmOut0: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    api_EthernetFramesRxIn0.is_some() && !(GumboLib::rx_allow_outbound_frame(api_EthernetFramesRxIn0.unwrap())),
    api_VmmOut0.is_none() && api_MavlinkOut0.is_none())
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_17_rx0_no_input
  * @param api_EthernetFramesRxIn0 incoming event data port
  * @param api_MavlinkOut0 outgoing event data port
  * @param api_VmmOut0 outgoing event data port
  */
pub fn compute_spec_hlr_17_rx0_no_input_guarantee(
  api_EthernetFramesRxIn0: Option<SW::RawEthernetMessage>,
  api_MavlinkOut0: Option<SW::UdpFrame_Impl>,
  api_VmmOut0: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    !(api_EthernetFramesRxIn0.is_some()),
    api_VmmOut0.is_none() && api_MavlinkOut0.is_none())
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_05_rx1_can_send_arp_to_vmm
  * @param api_EthernetFramesRxIn1 incoming event data port
  * @param api_MavlinkOut1 outgoing event data port
  * @param api_VmmOut1 outgoing event data port
  */
pub fn compute_spec_hlr_05_rx1_can_send_arp_to_vmm_guarantee(
  api_EthernetFramesRxIn1: Option<SW::RawEthernetMessage>,
  api_MavlinkOut1: Option<SW::UdpFrame_Impl>,
  api_VmmOut1: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    api_EthernetFramesRxIn1.is_some() && GumboLib::valid_arp(api_EthernetFramesRxIn1.unwrap()),
    api_VmmOut1.is_some() &&
      ((api_EthernetFramesRxIn1.unwrap() == api_VmmOut1.unwrap()) &&
        api_MavlinkOut1.is_none()))
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_18_rx1_can_send_mavlink_udp
  * @param api_EthernetFramesRxIn1 incoming event data port
  * @param api_MavlinkOut1 outgoing event data port
  * @param api_VmmOut1 outgoing event data port
  */
pub fn compute_spec_hlr_18_rx1_can_send_mavlink_udp_guarantee(
  api_EthernetFramesRxIn1: Option<SW::RawEthernetMessage>,
  api_MavlinkOut1: Option<SW::UdpFrame_Impl>,
  api_VmmOut1: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    api_EthernetFramesRxIn1.is_some() && GumboLib::valid_ipv4_udp_mavlink(api_EthernetFramesRxIn1.unwrap()),
    api_MavlinkOut1.is_some() &&
      (GumboLib::input_eq_mav_output(api_EthernetFramesRxIn1.unwrap(), api_MavlinkOut1.unwrap()) && api_VmmOut1.is_none()))
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_13_rx1_can_send_ipv4_udp
  * @param api_EthernetFramesRxIn1 incoming event data port
  * @param api_MavlinkOut1 outgoing event data port
  * @param api_VmmOut1 outgoing event data port
  */
pub fn compute_spec_hlr_13_rx1_can_send_ipv4_udp_guarantee(
  api_EthernetFramesRxIn1: Option<SW::RawEthernetMessage>,
  api_MavlinkOut1: Option<SW::UdpFrame_Impl>,
  api_VmmOut1: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    api_EthernetFramesRxIn1.is_some() && GumboLib::valid_ipv4_udp_port(api_EthernetFramesRxIn1.unwrap()),
    api_VmmOut1.is_some() &&
      ((api_EthernetFramesRxIn1.unwrap() == api_VmmOut1.unwrap()) &&
        api_MavlinkOut1.is_none()))
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_15_rx1_disallow
  * @param api_EthernetFramesRxIn1 incoming event data port
  * @param api_MavlinkOut1 outgoing event data port
  * @param api_VmmOut1 outgoing event data port
  */
pub fn compute_spec_hlr_15_rx1_disallow_guarantee(
  api_EthernetFramesRxIn1: Option<SW::RawEthernetMessage>,
  api_MavlinkOut1: Option<SW::UdpFrame_Impl>,
  api_VmmOut1: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    api_EthernetFramesRxIn1.is_some() && !(GumboLib::rx_allow_outbound_frame(api_EthernetFramesRxIn1.unwrap())),
    api_VmmOut1.is_none() && api_MavlinkOut1.is_none())
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_17_rx1_no_input
  * @param api_EthernetFramesRxIn1 incoming event data port
  * @param api_MavlinkOut1 outgoing event data port
  * @param api_VmmOut1 outgoing event data port
  */
pub fn compute_spec_hlr_17_rx1_no_input_guarantee(
  api_EthernetFramesRxIn1: Option<SW::RawEthernetMessage>,
  api_MavlinkOut1: Option<SW::UdpFrame_Impl>,
  api_VmmOut1: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    !(api_EthernetFramesRxIn1.is_some()),
    api_VmmOut1.is_none() && api_MavlinkOut1.is_none())
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_05_rx2_can_send_arp_to_vmm
  * @param api_EthernetFramesRxIn2 incoming event data port
  * @param api_MavlinkOut2 outgoing event data port
  * @param api_VmmOut2 outgoing event data port
  */
pub fn compute_spec_hlr_05_rx2_can_send_arp_to_vmm_guarantee(
  api_EthernetFramesRxIn2: Option<SW::RawEthernetMessage>,
  api_MavlinkOut2: Option<SW::UdpFrame_Impl>,
  api_VmmOut2: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    api_EthernetFramesRxIn2.is_some() && GumboLib::valid_arp(api_EthernetFramesRxIn2.unwrap()),
    api_VmmOut2.is_some() &&
      ((api_EthernetFramesRxIn2.unwrap() == api_VmmOut2.unwrap()) &&
        api_MavlinkOut2.is_none()))
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_18_rx2_can_send_mavlink_udp
  * @param api_EthernetFramesRxIn2 incoming event data port
  * @param api_MavlinkOut2 outgoing event data port
  * @param api_VmmOut2 outgoing event data port
  */
pub fn compute_spec_hlr_18_rx2_can_send_mavlink_udp_guarantee(
  api_EthernetFramesRxIn2: Option<SW::RawEthernetMessage>,
  api_MavlinkOut2: Option<SW::UdpFrame_Impl>,
  api_VmmOut2: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    api_EthernetFramesRxIn2.is_some() && GumboLib::valid_ipv4_udp_mavlink(api_EthernetFramesRxIn2.unwrap()),
    api_MavlinkOut2.is_some() &&
      (GumboLib::input_eq_mav_output(api_EthernetFramesRxIn2.unwrap(), api_MavlinkOut2.unwrap()) && api_VmmOut2.is_none()))
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_13_rx2_can_send_ipv4_udp
  * @param api_EthernetFramesRxIn2 incoming event data port
  * @param api_MavlinkOut2 outgoing event data port
  * @param api_VmmOut2 outgoing event data port
  */
pub fn compute_spec_hlr_13_rx2_can_send_ipv4_udp_guarantee(
  api_EthernetFramesRxIn2: Option<SW::RawEthernetMessage>,
  api_MavlinkOut2: Option<SW::UdpFrame_Impl>,
  api_VmmOut2: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    api_EthernetFramesRxIn2.is_some() && GumboLib::valid_ipv4_udp_port(api_EthernetFramesRxIn2.unwrap()),
    api_VmmOut2.is_some() &&
      ((api_EthernetFramesRxIn2.unwrap() == api_VmmOut2.unwrap()) &&
        api_MavlinkOut2.is_none()))
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_15_rx2_disallow
  * @param api_EthernetFramesRxIn2 incoming event data port
  * @param api_MavlinkOut2 outgoing event data port
  * @param api_VmmOut2 outgoing event data port
  */
pub fn compute_spec_hlr_15_rx2_disallow_guarantee(
  api_EthernetFramesRxIn2: Option<SW::RawEthernetMessage>,
  api_MavlinkOut2: Option<SW::UdpFrame_Impl>,
  api_VmmOut2: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    api_EthernetFramesRxIn2.is_some() && !(GumboLib::rx_allow_outbound_frame(api_EthernetFramesRxIn2.unwrap())),
    api_VmmOut2.is_none() && api_MavlinkOut2.is_none())
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_17_rx2_no_input
  * @param api_EthernetFramesRxIn2 incoming event data port
  * @param api_MavlinkOut2 outgoing event data port
  * @param api_VmmOut2 outgoing event data port
  */
pub fn compute_spec_hlr_17_rx2_no_input_guarantee(
  api_EthernetFramesRxIn2: Option<SW::RawEthernetMessage>,
  api_MavlinkOut2: Option<SW::UdpFrame_Impl>,
  api_VmmOut2: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    !(api_EthernetFramesRxIn2.is_some()),
    api_VmmOut2.is_none() && api_MavlinkOut2.is_none())
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_05_rx3_can_send_arp_to_vmm
  * @param api_EthernetFramesRxIn3 incoming event data port
  * @param api_MavlinkOut3 outgoing event data port
  * @param api_VmmOut3 outgoing event data port
  */
pub fn compute_spec_hlr_05_rx3_can_send_arp_to_vmm_guarantee(
  api_EthernetFramesRxIn3: Option<SW::RawEthernetMessage>,
  api_MavlinkOut3: Option<SW::UdpFrame_Impl>,
  api_VmmOut3: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    api_EthernetFramesRxIn3.is_some() && GumboLib::valid_arp(api_EthernetFramesRxIn3.unwrap()),
    api_VmmOut3.is_some() &&
      ((api_EthernetFramesRxIn3.unwrap() == api_VmmOut3.unwrap()) &&
        api_MavlinkOut3.is_none()))
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_18_rx3_can_send_mavlink_udp
  * @param api_EthernetFramesRxIn3 incoming event data port
  * @param api_MavlinkOut3 outgoing event data port
  * @param api_VmmOut3 outgoing event data port
  */
pub fn compute_spec_hlr_18_rx3_can_send_mavlink_udp_guarantee(
  api_EthernetFramesRxIn3: Option<SW::RawEthernetMessage>,
  api_MavlinkOut3: Option<SW::UdpFrame_Impl>,
  api_VmmOut3: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    api_EthernetFramesRxIn3.is_some() && GumboLib::valid_ipv4_udp_mavlink(api_EthernetFramesRxIn3.unwrap()),
    api_MavlinkOut3.is_some() &&
      (GumboLib::input_eq_mav_output(api_EthernetFramesRxIn3.unwrap(), api_MavlinkOut3.unwrap()) && api_VmmOut3.is_none()))
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_13_rx3_can_send_ipv4_udp
  * @param api_EthernetFramesRxIn3 incoming event data port
  * @param api_MavlinkOut3 outgoing event data port
  * @param api_VmmOut3 outgoing event data port
  */
pub fn compute_spec_hlr_13_rx3_can_send_ipv4_udp_guarantee(
  api_EthernetFramesRxIn3: Option<SW::RawEthernetMessage>,
  api_MavlinkOut3: Option<SW::UdpFrame_Impl>,
  api_VmmOut3: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    api_EthernetFramesRxIn3.is_some() && GumboLib::valid_ipv4_udp_port(api_EthernetFramesRxIn3.unwrap()),
    api_VmmOut3.is_some() &&
      ((api_EthernetFramesRxIn3.unwrap() == api_VmmOut3.unwrap()) &&
        api_MavlinkOut3.is_none()))
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_15_rx3_disallow
  * @param api_EthernetFramesRxIn3 incoming event data port
  * @param api_MavlinkOut3 outgoing event data port
  * @param api_VmmOut3 outgoing event data port
  */
pub fn compute_spec_hlr_15_rx3_disallow_guarantee(
  api_EthernetFramesRxIn3: Option<SW::RawEthernetMessage>,
  api_MavlinkOut3: Option<SW::UdpFrame_Impl>,
  api_VmmOut3: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    api_EthernetFramesRxIn3.is_some() && !(GumboLib::rx_allow_outbound_frame(api_EthernetFramesRxIn3.unwrap())),
    api_VmmOut3.is_none() && api_MavlinkOut3.is_none())
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_17_rx3_no_input
  * @param api_EthernetFramesRxIn3 incoming event data port
  * @param api_MavlinkOut3 outgoing event data port
  * @param api_VmmOut3 outgoing event data port
  */
pub fn compute_spec_hlr_17_rx3_no_input_guarantee(
  api_EthernetFramesRxIn3: Option<SW::RawEthernetMessage>,
  api_MavlinkOut3: Option<SW::UdpFrame_Impl>,
  api_VmmOut3: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    !(api_EthernetFramesRxIn3.is_some()),
    api_VmmOut3.is_none() && api_MavlinkOut3.is_none())
}

/** CEP-T-Guar: Top-level guarantee contracts for RxFirewall's compute entrypoint
  *
  * @param api_EthernetFramesRxIn0 incoming event data port
  * @param api_EthernetFramesRxIn1 incoming event data port
  * @param api_EthernetFramesRxIn2 incoming event data port
  * @param api_EthernetFramesRxIn3 incoming event data port
  * @param api_MavlinkOut0 outgoing event data port
  * @param api_MavlinkOut1 outgoing event data port
  * @param api_MavlinkOut2 outgoing event data port
  * @param api_MavlinkOut3 outgoing event data port
  * @param api_VmmOut0 outgoing event data port
  * @param api_VmmOut1 outgoing event data port
  * @param api_VmmOut2 outgoing event data port
  * @param api_VmmOut3 outgoing event data port
  */
pub fn compute_CEP_T_Guar(
  api_EthernetFramesRxIn0: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRxIn1: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRxIn2: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRxIn3: Option<SW::RawEthernetMessage>,
  api_MavlinkOut0: Option<SW::UdpFrame_Impl>,
  api_MavlinkOut1: Option<SW::UdpFrame_Impl>,
  api_MavlinkOut2: Option<SW::UdpFrame_Impl>,
  api_MavlinkOut3: Option<SW::UdpFrame_Impl>,
  api_VmmOut0: Option<SW::RawEthernetMessage>,
  api_VmmOut1: Option<SW::RawEthernetMessage>,
  api_VmmOut2: Option<SW::RawEthernetMessage>,
  api_VmmOut3: Option<SW::RawEthernetMessage>) -> bool
{
  let r0: bool = compute_spec_hlr_05_rx0_can_send_arp_to_vmm_guarantee(api_EthernetFramesRxIn0, api_MavlinkOut0, api_VmmOut0);
  let r1: bool = compute_spec_hlr_18_rx0_can_send_mavlink_udp_guarantee(api_EthernetFramesRxIn0, api_MavlinkOut0, api_VmmOut0);
  let r2: bool = compute_spec_hlr_13_rx0_can_send_ipv4_udp_guarantee(api_EthernetFramesRxIn0, api_MavlinkOut0, api_VmmOut0);
  let r3: bool = compute_spec_hlr_15_rx0_disallow_guarantee(api_EthernetFramesRxIn0, api_MavlinkOut0, api_VmmOut0);
  let r4: bool = compute_spec_hlr_17_rx0_no_input_guarantee(api_EthernetFramesRxIn0, api_MavlinkOut0, api_VmmOut0);
  let r5: bool = compute_spec_hlr_05_rx1_can_send_arp_to_vmm_guarantee(api_EthernetFramesRxIn1, api_MavlinkOut1, api_VmmOut1);
  let r6: bool = compute_spec_hlr_18_rx1_can_send_mavlink_udp_guarantee(api_EthernetFramesRxIn1, api_MavlinkOut1, api_VmmOut1);
  let r7: bool = compute_spec_hlr_13_rx1_can_send_ipv4_udp_guarantee(api_EthernetFramesRxIn1, api_MavlinkOut1, api_VmmOut1);
  let r8: bool = compute_spec_hlr_15_rx1_disallow_guarantee(api_EthernetFramesRxIn1, api_MavlinkOut1, api_VmmOut1);
  let r9: bool = compute_spec_hlr_17_rx1_no_input_guarantee(api_EthernetFramesRxIn1, api_MavlinkOut1, api_VmmOut1);
  let r10: bool = compute_spec_hlr_05_rx2_can_send_arp_to_vmm_guarantee(api_EthernetFramesRxIn2, api_MavlinkOut2, api_VmmOut2);
  let r11: bool = compute_spec_hlr_18_rx2_can_send_mavlink_udp_guarantee(api_EthernetFramesRxIn2, api_MavlinkOut2, api_VmmOut2);
  let r12: bool = compute_spec_hlr_13_rx2_can_send_ipv4_udp_guarantee(api_EthernetFramesRxIn2, api_MavlinkOut2, api_VmmOut2);
  let r13: bool = compute_spec_hlr_15_rx2_disallow_guarantee(api_EthernetFramesRxIn2, api_MavlinkOut2, api_VmmOut2);
  let r14: bool = compute_spec_hlr_17_rx2_no_input_guarantee(api_EthernetFramesRxIn2, api_MavlinkOut2, api_VmmOut2);
  let r15: bool = compute_spec_hlr_05_rx3_can_send_arp_to_vmm_guarantee(api_EthernetFramesRxIn3, api_MavlinkOut3, api_VmmOut3);
  let r16: bool = compute_spec_hlr_18_rx3_can_send_mavlink_udp_guarantee(api_EthernetFramesRxIn3, api_MavlinkOut3, api_VmmOut3);
  let r17: bool = compute_spec_hlr_13_rx3_can_send_ipv4_udp_guarantee(api_EthernetFramesRxIn3, api_MavlinkOut3, api_VmmOut3);
  let r18: bool = compute_spec_hlr_15_rx3_disallow_guarantee(api_EthernetFramesRxIn3, api_MavlinkOut3, api_VmmOut3);
  let r19: bool = compute_spec_hlr_17_rx3_no_input_guarantee(api_EthernetFramesRxIn3, api_MavlinkOut3, api_VmmOut3);

  return r0 && r1 && r2 && r3 && r4 && r5 && r6 && r7 && r8 && r9 && r10 && r11 && r12 && r13 && r14 && r15 && r16 && r17 && r18 && r19;
}

/** CEP-Post: Compute Entrypoint Post-Condition for RxFirewall
  *
  * @param api_EthernetFramesRxIn0 incoming event data port
  * @param api_EthernetFramesRxIn1 incoming event data port
  * @param api_EthernetFramesRxIn2 incoming event data port
  * @param api_EthernetFramesRxIn3 incoming event data port
  * @param api_MavlinkOut0 outgoing event data port
  * @param api_MavlinkOut1 outgoing event data port
  * @param api_MavlinkOut2 outgoing event data port
  * @param api_MavlinkOut3 outgoing event data port
  * @param api_VmmOut0 outgoing event data port
  * @param api_VmmOut1 outgoing event data port
  * @param api_VmmOut2 outgoing event data port
  * @param api_VmmOut3 outgoing event data port
  */
pub fn compute_CEP_Post(
  api_EthernetFramesRxIn0: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRxIn1: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRxIn2: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRxIn3: Option<SW::RawEthernetMessage>,
  api_MavlinkOut0: Option<SW::UdpFrame_Impl>,
  api_MavlinkOut1: Option<SW::UdpFrame_Impl>,
  api_MavlinkOut2: Option<SW::UdpFrame_Impl>,
  api_MavlinkOut3: Option<SW::UdpFrame_Impl>,
  api_VmmOut0: Option<SW::RawEthernetMessage>,
  api_VmmOut1: Option<SW::RawEthernetMessage>,
  api_VmmOut2: Option<SW::RawEthernetMessage>,
  api_VmmOut3: Option<SW::RawEthernetMessage>) -> bool
{
  // CEP-Guar: guarantee clauses of RxFirewall's compute entrypoint
  let r0: bool = compute_CEP_T_Guar(api_EthernetFramesRxIn0, api_EthernetFramesRxIn1, api_EthernetFramesRxIn2, api_EthernetFramesRxIn3, api_MavlinkOut0, api_MavlinkOut1, api_MavlinkOut2, api_MavlinkOut3, api_VmmOut0, api_VmmOut1, api_VmmOut2, api_VmmOut3);

  return r0;
}
