// Do not edit this file as it will be overwritten if codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_EthernetFramesRxIn0: Option<SW::RawEthernetMessage>,
  pub api_EthernetFramesRxIn1: Option<SW::RawEthernetMessage>,
  pub api_EthernetFramesRxIn2: Option<SW::RawEthernetMessage>,
  pub api_EthernetFramesRxIn3: Option<SW::RawEthernetMessage>
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_EthernetFramesRxIn0(container.api_EthernetFramesRxIn0);
  put_EthernetFramesRxIn1(container.api_EthernetFramesRxIn1);
  put_EthernetFramesRxIn2(container.api_EthernetFramesRxIn2);
  put_EthernetFramesRxIn3(container.api_EthernetFramesRxIn3);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(
  EthernetFramesRxIn0: Option<SW::RawEthernetMessage>,
  EthernetFramesRxIn1: Option<SW::RawEthernetMessage>,
  EthernetFramesRxIn2: Option<SW::RawEthernetMessage>,
  EthernetFramesRxIn3: Option<SW::RawEthernetMessage>)
{
  put_EthernetFramesRxIn0(EthernetFramesRxIn0);
  put_EthernetFramesRxIn1(EthernetFramesRxIn1);
  put_EthernetFramesRxIn2(EthernetFramesRxIn2);
  put_EthernetFramesRxIn3(EthernetFramesRxIn3);
}

/// setter for IN EventDataPort
pub fn put_EthernetFramesRxIn0(value: Option<SW::RawEthernetMessage>)
{
  *extern_api::IN_EthernetFramesRxIn0.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// setter for IN EventDataPort
pub fn put_EthernetFramesRxIn1(value: Option<SW::RawEthernetMessage>)
{
  *extern_api::IN_EthernetFramesRxIn1.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// setter for IN EventDataPort
pub fn put_EthernetFramesRxIn2(value: Option<SW::RawEthernetMessage>)
{
  *extern_api::IN_EthernetFramesRxIn2.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// setter for IN EventDataPort
pub fn put_EthernetFramesRxIn3(value: Option<SW::RawEthernetMessage>)
{
  *extern_api::IN_EthernetFramesRxIn3.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// getter for OUT EventDataPort
pub fn get_VmmOut0() -> Option<SW::RawEthernetMessage>
{
  return extern_api::OUT_VmmOut0.lock().unwrap_or_else(|e| e.into_inner()).clone()
}

/// getter for OUT EventDataPort
pub fn get_VmmOut1() -> Option<SW::RawEthernetMessage>
{
  return extern_api::OUT_VmmOut1.lock().unwrap_or_else(|e| e.into_inner()).clone()
}

/// getter for OUT EventDataPort
pub fn get_VmmOut2() -> Option<SW::RawEthernetMessage>
{
  return extern_api::OUT_VmmOut2.lock().unwrap_or_else(|e| e.into_inner()).clone()
}

/// getter for OUT EventDataPort
pub fn get_VmmOut3() -> Option<SW::RawEthernetMessage>
{
  return extern_api::OUT_VmmOut3.lock().unwrap_or_else(|e| e.into_inner()).clone()
}

/// getter for OUT EventDataPort
pub fn get_MavlinkOut0() -> Option<SW::UdpFrame_Impl>
{
  return extern_api::OUT_MavlinkOut0.lock().unwrap_or_else(|e| e.into_inner()).clone()
}

/// getter for OUT EventDataPort
pub fn get_MavlinkOut1() -> Option<SW::UdpFrame_Impl>
{
  return extern_api::OUT_MavlinkOut1.lock().unwrap_or_else(|e| e.into_inner()).clone()
}

/// getter for OUT EventDataPort
pub fn get_MavlinkOut2() -> Option<SW::UdpFrame_Impl>
{
  return extern_api::OUT_MavlinkOut2.lock().unwrap_or_else(|e| e.into_inner()).clone()
}

/// getter for OUT EventDataPort
pub fn get_MavlinkOut3() -> Option<SW::UdpFrame_Impl>
{
  return extern_api::OUT_MavlinkOut3.lock().unwrap_or_else(|e| e.into_inner()).clone()
}
