// Do not edit this file as it will be overwritten if codegen is rerun

//! C-interface for the component.
//! This code must be unsafe.
//! Assumptions about correctness are introduced and need to be verified by other means.

use data::*;

#[cfg(test)]
use std::sync::Mutex;

#[cfg(not(test))]
extern "C" {
  fn get_In0(value: *mut SW::UdpFrame_Impl) -> bool;
  fn get_In1(value: *mut SW::UdpFrame_Impl) -> bool;
  fn get_In2(value: *mut SW::UdpFrame_Impl) -> bool;
  fn get_In3(value: *mut SW::UdpFrame_Impl) -> bool;
  fn put_Out0(value: *mut SW::RawEthernetMessage) -> bool;
  fn put_Out1(value: *mut SW::RawEthernetMessage) -> bool;
  fn put_Out2(value: *mut SW::RawEthernetMessage) -> bool;
  fn put_Out3(value: *mut SW::RawEthernetMessage) -> bool;
}

pub fn unsafe_get_In0() -> Option<SW::UdpFrame_Impl>
{
  unsafe {
    let value: *mut SW::UdpFrame_Impl = &mut SW::UdpFrame_Impl::default();
    if (get_In0(value)) {
      return Some(*value);
    } else {
      return None;
    }
  }
}

pub fn unsafe_get_In1() -> Option<SW::UdpFrame_Impl>
{
  unsafe {
    let value: *mut SW::UdpFrame_Impl = &mut SW::UdpFrame_Impl::default();
    if (get_In1(value)) {
      return Some(*value);
    } else {
      return None;
    }
  }
}

pub fn unsafe_get_In2() -> Option<SW::UdpFrame_Impl>
{
  unsafe {
    let value: *mut SW::UdpFrame_Impl = &mut SW::UdpFrame_Impl::default();
    if (get_In2(value)) {
      return Some(*value);
    } else {
      return None;
    }
  }
}

pub fn unsafe_get_In3() -> Option<SW::UdpFrame_Impl>
{
  unsafe {
    let value: *mut SW::UdpFrame_Impl = &mut SW::UdpFrame_Impl::default();
    if (get_In3(value)) {
      return Some(*value);
    } else {
      return None;
    }
  }
}

pub fn unsafe_put_Out0(value: &SW::RawEthernetMessage) -> bool
{
  unsafe {
    return put_Out0(value as *const SW::RawEthernetMessage as *mut SW::RawEthernetMessage);
  }
}

pub fn unsafe_put_Out1(value: &SW::RawEthernetMessage) -> bool
{
  unsafe {
    return put_Out1(value as *const SW::RawEthernetMessage as *mut SW::RawEthernetMessage);
  }
}

pub fn unsafe_put_Out2(value: &SW::RawEthernetMessage) -> bool
{
  unsafe {
    return put_Out2(value as *const SW::RawEthernetMessage as *mut SW::RawEthernetMessage);
  }
}

pub fn unsafe_put_Out3(value: &SW::RawEthernetMessage) -> bool
{
  unsafe {
    return put_Out3(value as *const SW::RawEthernetMessage as *mut SW::RawEthernetMessage);
  }
}

//////////////////////////////////////////////////////////////////////////////////
// Testing Versions
//////////////////////////////////////////////////////////////////////////////////

#[cfg(test)]
lazy_static::lazy_static! {
  // simulate the global C variables that point to the microkit shared memory regions.  In a full
  // microkit system we would be able to mutate the shared memory for out ports since they're r/w,
  // but we couldn't do that for in ports since they are read-only
  pub static ref IN_In0: Mutex<Option<SW::UdpFrame_Impl>> = Mutex::new(None);
  pub static ref IN_In1: Mutex<Option<SW::UdpFrame_Impl>> = Mutex::new(None);
  pub static ref IN_In2: Mutex<Option<SW::UdpFrame_Impl>> = Mutex::new(None);
  pub static ref IN_In3: Mutex<Option<SW::UdpFrame_Impl>> = Mutex::new(None);
  pub static ref OUT_Out0: Mutex<Option<SW::RawEthernetMessage>> = Mutex::new(None);
  pub static ref OUT_Out1: Mutex<Option<SW::RawEthernetMessage>> = Mutex::new(None);
  pub static ref OUT_Out2: Mutex<Option<SW::RawEthernetMessage>> = Mutex::new(None);
  pub static ref OUT_Out3: Mutex<Option<SW::RawEthernetMessage>> = Mutex::new(None);
}

#[cfg(test)]
pub fn initialize_test_globals() {
  unsafe {
    *IN_In0.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_In1.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_In2.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_In3.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_Out0.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_Out1.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_Out2.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_Out3.lock().unwrap_or_else(|e| e.into_inner()) = None;
  }
}

#[cfg(test)]
pub fn get_In0(value: *mut SW::UdpFrame_Impl) -> bool
{
  unsafe {
    match *IN_In0.lock().unwrap_or_else(|e| e.into_inner()) {
      Some(v) => {
        *value = v;
        return true;
      },
      None => return false,
    }
  }
}

#[cfg(test)]
pub fn get_In1(value: *mut SW::UdpFrame_Impl) -> bool
{
  unsafe {
    match *IN_In1.lock().unwrap_or_else(|e| e.into_inner()) {
      Some(v) => {
        *value = v;
        return true;
      },
      None => return false,
    }
  }
}

#[cfg(test)]
pub fn get_In2(value: *mut SW::UdpFrame_Impl) -> bool
{
  unsafe {
    match *IN_In2.lock().unwrap_or_else(|e| e.into_inner()) {
      Some(v) => {
        *value = v;
        return true;
      },
      None => return false,
    }
  }
}

#[cfg(test)]
pub fn get_In3(value: *mut SW::UdpFrame_Impl) -> bool
{
  unsafe {
    match *IN_In3.lock().unwrap_or_else(|e| e.into_inner()) {
      Some(v) => {
        *value = v;
        return true;
      },
      None => return false,
    }
  }
}

#[cfg(test)]
pub fn put_Out0(value: *mut SW::RawEthernetMessage) -> bool
{
  unsafe {
    *OUT_Out0.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}

#[cfg(test)]
pub fn put_Out1(value: *mut SW::RawEthernetMessage) -> bool
{
  unsafe {
    *OUT_Out1.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}

#[cfg(test)]
pub fn put_Out2(value: *mut SW::RawEthernetMessage) -> bool
{
  unsafe {
    *OUT_Out2.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}

#[cfg(test)]
pub fn put_Out3(value: *mut SW::RawEthernetMessage) -> bool
{
  unsafe {
    *OUT_Out3.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}
