// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {
  pub trait seL4_MavlinkFirewall_MavlinkFirewall_Api {}

  pub trait seL4_MavlinkFirewall_MavlinkFirewall_Put_Api: seL4_MavlinkFirewall_MavlinkFirewall_Api {
    #[verifier::external_body]
    fn unverified_put_Out0(
      &mut self,
      value: SW::RawEthernetMessage)
    {
      extern_api::unsafe_put_Out0(&value);
    }

    #[verifier::external_body]
    fn unverified_put_Out1(
      &mut self,
      value: SW::RawEthernetMessage)
    {
      extern_api::unsafe_put_Out1(&value);
    }

    #[verifier::external_body]
    fn unverified_put_Out2(
      &mut self,
      value: SW::RawEthernetMessage)
    {
      extern_api::unsafe_put_Out2(&value);
    }

    #[verifier::external_body]
    fn unverified_put_Out3(
      &mut self,
      value: SW::RawEthernetMessage)
    {
      extern_api::unsafe_put_Out3(&value);
    }
  }

  pub trait seL4_MavlinkFirewall_MavlinkFirewall_Get_Api: seL4_MavlinkFirewall_MavlinkFirewall_Api {
    #[verifier::external_body]
    fn unverified_get_In0(
      &mut self,
      value: &Ghost<Option<SW::UdpFrame_Impl>>) -> (res : Option<SW::UdpFrame_Impl>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_In0();
    }

    #[verifier::external_body]
    fn unverified_get_In1(
      &mut self,
      value: &Ghost<Option<SW::UdpFrame_Impl>>) -> (res : Option<SW::UdpFrame_Impl>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_In1();
    }

    #[verifier::external_body]
    fn unverified_get_In2(
      &mut self,
      value: &Ghost<Option<SW::UdpFrame_Impl>>) -> (res : Option<SW::UdpFrame_Impl>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_In2();
    }

    #[verifier::external_body]
    fn unverified_get_In3(
      &mut self,
      value: &Ghost<Option<SW::UdpFrame_Impl>>) -> (res : Option<SW::UdpFrame_Impl>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_In3();
    }
  }

  pub trait seL4_MavlinkFirewall_MavlinkFirewall_Full_Api: seL4_MavlinkFirewall_MavlinkFirewall_Put_Api + seL4_MavlinkFirewall_MavlinkFirewall_Get_Api {}

  pub struct seL4_MavlinkFirewall_MavlinkFirewall_Application_Api<API: seL4_MavlinkFirewall_MavlinkFirewall_Api> {
    pub api: API,

    pub ghost In0: Option<SW::UdpFrame_Impl>,
    pub ghost In1: Option<SW::UdpFrame_Impl>,
    pub ghost In2: Option<SW::UdpFrame_Impl>,
    pub ghost In3: Option<SW::UdpFrame_Impl>,
    pub ghost Out0: Option<SW::RawEthernetMessage>,
    pub ghost Out1: Option<SW::RawEthernetMessage>,
    pub ghost Out2: Option<SW::RawEthernetMessage>,
    pub ghost Out3: Option<SW::RawEthernetMessage>
  }

  impl<API: seL4_MavlinkFirewall_MavlinkFirewall_Put_Api> seL4_MavlinkFirewall_MavlinkFirewall_Application_Api<API> {
    pub fn put_Out0(
      &mut self,
      value: SW::RawEthernetMessage)
      ensures
        old(self).In0 == self.In0,
        old(self).In1 == self.In1,
        old(self).In2 == self.In2,
        old(self).In3 == self.In3,
        self.Out0 == Some(value),
        old(self).Out1 == self.Out1,
        old(self).Out2 == self.Out2,
        old(self).Out3 == self.Out3,
    {
      self.api.unverified_put_Out0(value);
      self.Out0 = Some(value);
    }
    pub fn put_Out1(
      &mut self,
      value: SW::RawEthernetMessage)
      ensures
        old(self).In0 == self.In0,
        old(self).In1 == self.In1,
        old(self).In2 == self.In2,
        old(self).In3 == self.In3,
        old(self).Out0 == self.Out0,
        self.Out1 == Some(value),
        old(self).Out2 == self.Out2,
        old(self).Out3 == self.Out3,
    {
      self.api.unverified_put_Out1(value);
      self.Out1 = Some(value);
    }
    pub fn put_Out2(
      &mut self,
      value: SW::RawEthernetMessage)
      ensures
        old(self).In0 == self.In0,
        old(self).In1 == self.In1,
        old(self).In2 == self.In2,
        old(self).In3 == self.In3,
        old(self).Out0 == self.Out0,
        old(self).Out1 == self.Out1,
        self.Out2 == Some(value),
        old(self).Out3 == self.Out3,
    {
      self.api.unverified_put_Out2(value);
      self.Out2 = Some(value);
    }
    pub fn put_Out3(
      &mut self,
      value: SW::RawEthernetMessage)
      ensures
        old(self).In0 == self.In0,
        old(self).In1 == self.In1,
        old(self).In2 == self.In2,
        old(self).In3 == self.In3,
        old(self).Out0 == self.Out0,
        old(self).Out1 == self.Out1,
        old(self).Out2 == self.Out2,
        self.Out3 == Some(value),
    {
      self.api.unverified_put_Out3(value);
      self.Out3 = Some(value);
    }
  }

  impl<API: seL4_MavlinkFirewall_MavlinkFirewall_Get_Api> seL4_MavlinkFirewall_MavlinkFirewall_Application_Api<API> {
    pub fn get_In0(&mut self) -> (res : Option<SW::UdpFrame_Impl>)
      ensures
        old(self).In0 == self.In0,
        res == self.In0,
        old(self).In1 == self.In1,
        old(self).In2 == self.In2,
        old(self).In3 == self.In3,
        old(self).Out0 == self.Out0,
        old(self).Out1 == self.Out1,
        old(self).Out2 == self.Out2,
        old(self).Out3 == self.Out3,
    {
      self.api.unverified_get_In0(&Ghost(self.In0))
    }
    pub fn get_In1(&mut self) -> (res : Option<SW::UdpFrame_Impl>)
      ensures
        old(self).In0 == self.In0,
        old(self).In1 == self.In1,
        res == self.In1,
        old(self).In2 == self.In2,
        old(self).In3 == self.In3,
        old(self).Out0 == self.Out0,
        old(self).Out1 == self.Out1,
        old(self).Out2 == self.Out2,
        old(self).Out3 == self.Out3,
    {
      self.api.unverified_get_In1(&Ghost(self.In1))
    }
    pub fn get_In2(&mut self) -> (res : Option<SW::UdpFrame_Impl>)
      ensures
        old(self).In0 == self.In0,
        old(self).In1 == self.In1,
        old(self).In2 == self.In2,
        res == self.In2,
        old(self).In3 == self.In3,
        old(self).Out0 == self.Out0,
        old(self).Out1 == self.Out1,
        old(self).Out2 == self.Out2,
        old(self).Out3 == self.Out3,
    {
      self.api.unverified_get_In2(&Ghost(self.In2))
    }
    pub fn get_In3(&mut self) -> (res : Option<SW::UdpFrame_Impl>)
      ensures
        old(self).In0 == self.In0,
        old(self).In1 == self.In1,
        old(self).In2 == self.In2,
        old(self).In3 == self.In3,
        res == self.In3,
        old(self).Out0 == self.Out0,
        old(self).Out1 == self.Out1,
        old(self).Out2 == self.Out2,
        old(self).Out3 == self.Out3,
    {
      self.api.unverified_get_In3(&Ghost(self.In3))
    }
  }

  pub struct seL4_MavlinkFirewall_MavlinkFirewall_Initialization_Api;
  impl seL4_MavlinkFirewall_MavlinkFirewall_Api for seL4_MavlinkFirewall_MavlinkFirewall_Initialization_Api {}
  impl seL4_MavlinkFirewall_MavlinkFirewall_Put_Api for seL4_MavlinkFirewall_MavlinkFirewall_Initialization_Api {}

  pub const fn init_api() -> seL4_MavlinkFirewall_MavlinkFirewall_Application_Api<seL4_MavlinkFirewall_MavlinkFirewall_Initialization_Api> {
    return seL4_MavlinkFirewall_MavlinkFirewall_Application_Api {
      api: seL4_MavlinkFirewall_MavlinkFirewall_Initialization_Api {},

      In0: None,
      In1: None,
      In2: None,
      In3: None,
      Out0: None,
      Out1: None,
      Out2: None,
      Out3: None
    }
  }

  pub struct seL4_MavlinkFirewall_MavlinkFirewall_Compute_Api;
  impl seL4_MavlinkFirewall_MavlinkFirewall_Api for seL4_MavlinkFirewall_MavlinkFirewall_Compute_Api {}
  impl seL4_MavlinkFirewall_MavlinkFirewall_Put_Api for seL4_MavlinkFirewall_MavlinkFirewall_Compute_Api {}
  impl seL4_MavlinkFirewall_MavlinkFirewall_Get_Api for seL4_MavlinkFirewall_MavlinkFirewall_Compute_Api {}
  impl seL4_MavlinkFirewall_MavlinkFirewall_Full_Api for seL4_MavlinkFirewall_MavlinkFirewall_Compute_Api {}

  pub const fn compute_api() -> seL4_MavlinkFirewall_MavlinkFirewall_Application_Api<seL4_MavlinkFirewall_MavlinkFirewall_Compute_Api> {
    return seL4_MavlinkFirewall_MavlinkFirewall_Application_Api {
      api: seL4_MavlinkFirewall_MavlinkFirewall_Compute_Api {},

      In0: None,
      In1: None,
      In2: None,
      In3: None,
      Out0: None,
      Out1: None,
      Out2: None,
      Out3: None
    }
  }
}