#include "seL4_RxFirewall_RxFirewall.h"

// Do not edit this file as it will be overwritten if codegen is rerun

void seL4_RxFirewall_RxFirewall_initialize(void);
void seL4_RxFirewall_RxFirewall_notify(microkit_channel channel);
void seL4_RxFirewall_RxFirewall_timeTriggered(void);

volatile sb_queue_SW_RawEthernetMessage_1_t *VmmOut0_queue_1;
volatile sb_queue_SW_RawEthernetMessage_1_t *VmmOut1_queue_1;
volatile sb_queue_SW_RawEthernetMessage_1_t *VmmOut2_queue_1;
volatile sb_queue_SW_RawEthernetMessage_1_t *VmmOut3_queue_1;
volatile sb_queue_SW_UdpFrame_Impl_1_t *MavlinkOut0_queue_1;
volatile sb_queue_SW_UdpFrame_Impl_1_t *MavlinkOut1_queue_1;
volatile sb_queue_SW_UdpFrame_Impl_1_t *MavlinkOut2_queue_1;
volatile sb_queue_SW_UdpFrame_Impl_1_t *MavlinkOut3_queue_1;
volatile sb_queue_SW_RawEthernetMessage_1_t *EthernetFramesRxIn0_queue_1;
sb_queue_SW_RawEthernetMessage_1_Recv_t EthernetFramesRxIn0_recv_queue;
volatile sb_queue_SW_RawEthernetMessage_1_t *EthernetFramesRxIn1_queue_1;
sb_queue_SW_RawEthernetMessage_1_Recv_t EthernetFramesRxIn1_recv_queue;
volatile sb_queue_SW_RawEthernetMessage_1_t *EthernetFramesRxIn2_queue_1;
sb_queue_SW_RawEthernetMessage_1_Recv_t EthernetFramesRxIn2_recv_queue;
volatile sb_queue_SW_RawEthernetMessage_1_t *EthernetFramesRxIn3_queue_1;
sb_queue_SW_RawEthernetMessage_1_Recv_t EthernetFramesRxIn3_recv_queue;

#define PORT_FROM_MON 56

bool put_VmmOut0(const SW_RawEthernetMessage *data) {
  sb_queue_SW_RawEthernetMessage_1_enqueue((sb_queue_SW_RawEthernetMessage_1_t *) VmmOut0_queue_1, (SW_RawEthernetMessage *) data);

  return true;
}

bool put_VmmOut1(const SW_RawEthernetMessage *data) {
  sb_queue_SW_RawEthernetMessage_1_enqueue((sb_queue_SW_RawEthernetMessage_1_t *) VmmOut1_queue_1, (SW_RawEthernetMessage *) data);

  return true;
}

bool put_VmmOut2(const SW_RawEthernetMessage *data) {
  sb_queue_SW_RawEthernetMessage_1_enqueue((sb_queue_SW_RawEthernetMessage_1_t *) VmmOut2_queue_1, (SW_RawEthernetMessage *) data);

  return true;
}

bool put_VmmOut3(const SW_RawEthernetMessage *data) {
  sb_queue_SW_RawEthernetMessage_1_enqueue((sb_queue_SW_RawEthernetMessage_1_t *) VmmOut3_queue_1, (SW_RawEthernetMessage *) data);

  return true;
}

bool put_MavlinkOut0(const SW_UdpFrame_Impl *data) {
  sb_queue_SW_UdpFrame_Impl_1_enqueue((sb_queue_SW_UdpFrame_Impl_1_t *) MavlinkOut0_queue_1, (SW_UdpFrame_Impl *) data);

  return true;
}

bool put_MavlinkOut1(const SW_UdpFrame_Impl *data) {
  sb_queue_SW_UdpFrame_Impl_1_enqueue((sb_queue_SW_UdpFrame_Impl_1_t *) MavlinkOut1_queue_1, (SW_UdpFrame_Impl *) data);

  return true;
}

bool put_MavlinkOut2(const SW_UdpFrame_Impl *data) {
  sb_queue_SW_UdpFrame_Impl_1_enqueue((sb_queue_SW_UdpFrame_Impl_1_t *) MavlinkOut2_queue_1, (SW_UdpFrame_Impl *) data);

  return true;
}

bool put_MavlinkOut3(const SW_UdpFrame_Impl *data) {
  sb_queue_SW_UdpFrame_Impl_1_enqueue((sb_queue_SW_UdpFrame_Impl_1_t *) MavlinkOut3_queue_1, (SW_UdpFrame_Impl *) data);

  return true;
}

bool EthernetFramesRxIn0_is_empty(void) {
  return sb_queue_SW_RawEthernetMessage_1_is_empty(&EthernetFramesRxIn0_recv_queue);
}

bool get_EthernetFramesRxIn0_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data) {
  return sb_queue_SW_RawEthernetMessage_1_dequeue((sb_queue_SW_RawEthernetMessage_1_Recv_t *) &EthernetFramesRxIn0_recv_queue, numDropped, data);
}

bool get_EthernetFramesRxIn0(SW_RawEthernetMessage *data) {
  sb_event_counter_t numDropped;
  return get_EthernetFramesRxIn0_poll (&numDropped, data);
}

bool EthernetFramesRxIn1_is_empty(void) {
  return sb_queue_SW_RawEthernetMessage_1_is_empty(&EthernetFramesRxIn1_recv_queue);
}

bool get_EthernetFramesRxIn1_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data) {
  return sb_queue_SW_RawEthernetMessage_1_dequeue((sb_queue_SW_RawEthernetMessage_1_Recv_t *) &EthernetFramesRxIn1_recv_queue, numDropped, data);
}

bool get_EthernetFramesRxIn1(SW_RawEthernetMessage *data) {
  sb_event_counter_t numDropped;
  return get_EthernetFramesRxIn1_poll (&numDropped, data);
}

bool EthernetFramesRxIn2_is_empty(void) {
  return sb_queue_SW_RawEthernetMessage_1_is_empty(&EthernetFramesRxIn2_recv_queue);
}

bool get_EthernetFramesRxIn2_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data) {
  return sb_queue_SW_RawEthernetMessage_1_dequeue((sb_queue_SW_RawEthernetMessage_1_Recv_t *) &EthernetFramesRxIn2_recv_queue, numDropped, data);
}

bool get_EthernetFramesRxIn2(SW_RawEthernetMessage *data) {
  sb_event_counter_t numDropped;
  return get_EthernetFramesRxIn2_poll (&numDropped, data);
}

bool EthernetFramesRxIn3_is_empty(void) {
  return sb_queue_SW_RawEthernetMessage_1_is_empty(&EthernetFramesRxIn3_recv_queue);
}

bool get_EthernetFramesRxIn3_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data) {
  return sb_queue_SW_RawEthernetMessage_1_dequeue((sb_queue_SW_RawEthernetMessage_1_Recv_t *) &EthernetFramesRxIn3_recv_queue, numDropped, data);
}

bool get_EthernetFramesRxIn3(SW_RawEthernetMessage *data) {
  sb_event_counter_t numDropped;
  return get_EthernetFramesRxIn3_poll (&numDropped, data);
}

void init(void) {
  sb_queue_SW_RawEthernetMessage_1_init((sb_queue_SW_RawEthernetMessage_1_t *) VmmOut0_queue_1);

  sb_queue_SW_RawEthernetMessage_1_init((sb_queue_SW_RawEthernetMessage_1_t *) VmmOut1_queue_1);

  sb_queue_SW_RawEthernetMessage_1_init((sb_queue_SW_RawEthernetMessage_1_t *) VmmOut2_queue_1);

  sb_queue_SW_RawEthernetMessage_1_init((sb_queue_SW_RawEthernetMessage_1_t *) VmmOut3_queue_1);

  sb_queue_SW_UdpFrame_Impl_1_init((sb_queue_SW_UdpFrame_Impl_1_t *) MavlinkOut0_queue_1);

  sb_queue_SW_UdpFrame_Impl_1_init((sb_queue_SW_UdpFrame_Impl_1_t *) MavlinkOut1_queue_1);

  sb_queue_SW_UdpFrame_Impl_1_init((sb_queue_SW_UdpFrame_Impl_1_t *) MavlinkOut2_queue_1);

  sb_queue_SW_UdpFrame_Impl_1_init((sb_queue_SW_UdpFrame_Impl_1_t *) MavlinkOut3_queue_1);

  sb_queue_SW_RawEthernetMessage_1_Recv_init(&EthernetFramesRxIn0_recv_queue, (sb_queue_SW_RawEthernetMessage_1_t *) EthernetFramesRxIn0_queue_1);

  sb_queue_SW_RawEthernetMessage_1_Recv_init(&EthernetFramesRxIn1_recv_queue, (sb_queue_SW_RawEthernetMessage_1_t *) EthernetFramesRxIn1_queue_1);

  sb_queue_SW_RawEthernetMessage_1_Recv_init(&EthernetFramesRxIn2_recv_queue, (sb_queue_SW_RawEthernetMessage_1_t *) EthernetFramesRxIn2_queue_1);

  sb_queue_SW_RawEthernetMessage_1_Recv_init(&EthernetFramesRxIn3_recv_queue, (sb_queue_SW_RawEthernetMessage_1_t *) EthernetFramesRxIn3_queue_1);

  seL4_RxFirewall_RxFirewall_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      seL4_RxFirewall_RxFirewall_timeTriggered();
      break;
    default:
      seL4_RxFirewall_RxFirewall_notify(channel);
  }
}
