// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

use proptest::prelude::*;

use super::test_apis::*;

use crate::bridge::seL4_RxFirewall_RxFirewall_GUMBOX as GUMBOX;

pub enum HarnessResult {
  RejectedPrecondition,
  FailedPostcondition(TestCaseError),
  Passed,
}

/** Contract-based test harness for the initialize entry point
  */
pub fn testInitializeCB() -> HarnessResult
{
  // [InvokeEntryPoint]: Invoke the entry point
  crate::seL4_RxFirewall_RxFirewall_initialize();

  return HarnessResult::Passed
}

#[macro_export]
macro_rules!
testInitializeCB_macro {
  (
    $test_name: ident,
    config: $config:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(empty in ::proptest::strategy::Just(())) {
        match $crate::test::util::cb_apis::testInitializeCB() {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            unreachable!("This branch is infeasible")
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}

/** Contract-based test harness for the compute entry point
  *
  * @param api_EthernetFramesRxIn0 incoming event data port
  * @param api_EthernetFramesRxIn1 incoming event data port
  * @param api_EthernetFramesRxIn2 incoming event data port
  * @param api_EthernetFramesRxIn3 incoming event data port
  */
pub fn testComputeCB(
  api_EthernetFramesRxIn0: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRxIn1: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRxIn2: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRxIn3: Option<SW::RawEthernetMessage>) -> HarnessResult
{
  // Initialize the app
  crate::seL4_RxFirewall_RxFirewall_initialize();

  // [PutInPorts]: Set values on the input ports
  put_EthernetFramesRxIn0(api_EthernetFramesRxIn0);
  put_EthernetFramesRxIn1(api_EthernetFramesRxIn1);
  put_EthernetFramesRxIn2(api_EthernetFramesRxIn2);
  put_EthernetFramesRxIn3(api_EthernetFramesRxIn3);

  // [InvokeEntryPoint]: Invoke the entry point
  crate::seL4_RxFirewall_RxFirewall_timeTriggered();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let api_MavlinkOut0 = get_MavlinkOut0();
  let api_MavlinkOut1 = get_MavlinkOut1();
  let api_MavlinkOut2 = get_MavlinkOut2();
  let api_MavlinkOut3 = get_MavlinkOut3();
  let api_VmmOut0 = get_VmmOut0();
  let api_VmmOut1 = get_VmmOut1();
  let api_VmmOut2 = get_VmmOut2();
  let api_VmmOut3 = get_VmmOut3();

  // [CheckPost]: invoke the oracle function
  if !GUMBOX::compute_CEP_Post(api_EthernetFramesRxIn0, api_EthernetFramesRxIn1, api_EthernetFramesRxIn2, api_EthernetFramesRxIn3, api_MavlinkOut0, api_MavlinkOut1, api_MavlinkOut2, api_MavlinkOut3, api_VmmOut0, api_VmmOut1, api_VmmOut2, api_VmmOut3) {
    return HarnessResult::FailedPostcondition(TestCaseError::Fail("Postcondition failed: incorrect output behavior".into()));
  }

  return HarnessResult::Passed
}

/** Contract-based test harness for the compute entry point
  */
pub fn testComputeCB_container(container: PreStateContainer) -> HarnessResult
{
  return testComputeCB(container.api_EthernetFramesRxIn0, container.api_EthernetFramesRxIn1, container.api_EthernetFramesRxIn2, container.api_EthernetFramesRxIn3)
}

#[macro_export]
macro_rules!
testComputeCB_macro {
  (
    $test_name: ident,
    config: $config:expr,
    api_EthernetFramesRxIn0: $api_EthernetFramesRxIn0_strat:expr,
    api_EthernetFramesRxIn1: $api_EthernetFramesRxIn1_strat:expr,
    api_EthernetFramesRxIn2: $api_EthernetFramesRxIn2_strat:expr,
    api_EthernetFramesRxIn3: $api_EthernetFramesRxIn3_strat:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(
        (api_EthernetFramesRxIn0, api_EthernetFramesRxIn1, api_EthernetFramesRxIn2, api_EthernetFramesRxIn3)
            in ($api_EthernetFramesRxIn0_strat, $api_EthernetFramesRxIn1_strat, $api_EthernetFramesRxIn2_strat, $api_EthernetFramesRxIn3_strat)
      ) {
        match$crate::test::util::cb_apis::testComputeCB(api_EthernetFramesRxIn0, api_EthernetFramesRxIn1, api_EthernetFramesRxIn2, api_EthernetFramesRxIn3) {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            return Err(proptest::test_runner::TestCaseError::reject(
              "Precondition failed: invalid input combination",
            ))
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}
