#pragma once

#include <printf.h>
#include <util.h>
#include <stdint.h>
#include <microkit.h>
#include <sb_types.h>

// Do not edit this file as it will be overwritten if codegen is rerun


bool put_Out0(const SW_RawEthernetMessage *data);
bool put_Out1(const SW_RawEthernetMessage *data);
bool put_Out2(const SW_RawEthernetMessage *data);
bool put_Out3(const SW_RawEthernetMessage *data);
bool In0_is_empty(void);
bool get_In0_poll(sb_event_counter_t *numDropped, SW_UdpFrame_Impl *data);
bool get_In0(SW_UdpFrame_Impl *data);
bool In1_is_empty(void);
bool get_In1_poll(sb_event_counter_t *numDropped, SW_UdpFrame_Impl *data);
bool get_In1(SW_UdpFrame_Impl *data);
bool In2_is_empty(void);
bool get_In2_poll(sb_event_counter_t *numDropped, SW_UdpFrame_Impl *data);
bool get_In2(SW_UdpFrame_Impl *data);
bool In3_is_empty(void);
bool get_In3_poll(sb_event_counter_t *numDropped, SW_UdpFrame_Impl *data);
bool get_In3(SW_UdpFrame_Impl *data);
