// Do not edit this file as it will be overwritten if codegen is rerun

//! C-interface for the component.
//! This code must be unsafe.
//! Assumptions about correctness are introduced and need to be verified by other means.

use data::*;

#[cfg(test)]
use std::sync::Mutex;

#[cfg(not(test))]
extern "C" {
  fn get_EthernetFramesTxIn0(value: *mut SW::RawEthernetMessage) -> bool;
  fn get_EthernetFramesTxIn1(value: *mut SW::RawEthernetMessage) -> bool;
  fn get_EthernetFramesTxIn2(value: *mut SW::RawEthernetMessage) -> bool;
  fn get_EthernetFramesTxIn3(value: *mut SW::RawEthernetMessage) -> bool;
  fn put_EthernetFramesTxOut0(value: *mut SW::SizedEthernetMessage_Impl) -> bool;
  fn put_EthernetFramesTxOut1(value: *mut SW::SizedEthernetMessage_Impl) -> bool;
  fn put_EthernetFramesTxOut2(value: *mut SW::SizedEthernetMessage_Impl) -> bool;
  fn put_EthernetFramesTxOut3(value: *mut SW::SizedEthernetMessage_Impl) -> bool;
}

pub fn unsafe_get_EthernetFramesTxIn0() -> Option<SW::RawEthernetMessage>
{
  unsafe {
    let value: *mut SW::RawEthernetMessage = &mut [0; SW::SW_RawEthernetMessage_DIM_0];
    if (get_EthernetFramesTxIn0(value)) {
      return Some(*value);
    } else {
      return None;
    }
  }
}

pub fn unsafe_get_EthernetFramesTxIn1() -> Option<SW::RawEthernetMessage>
{
  unsafe {
    let value: *mut SW::RawEthernetMessage = &mut [0; SW::SW_RawEthernetMessage_DIM_0];
    if (get_EthernetFramesTxIn1(value)) {
      return Some(*value);
    } else {
      return None;
    }
  }
}

pub fn unsafe_get_EthernetFramesTxIn2() -> Option<SW::RawEthernetMessage>
{
  unsafe {
    let value: *mut SW::RawEthernetMessage = &mut [0; SW::SW_RawEthernetMessage_DIM_0];
    if (get_EthernetFramesTxIn2(value)) {
      return Some(*value);
    } else {
      return None;
    }
  }
}

pub fn unsafe_get_EthernetFramesTxIn3() -> Option<SW::RawEthernetMessage>
{
  unsafe {
    let value: *mut SW::RawEthernetMessage = &mut [0; SW::SW_RawEthernetMessage_DIM_0];
    if (get_EthernetFramesTxIn3(value)) {
      return Some(*value);
    } else {
      return None;
    }
  }
}

pub fn unsafe_put_EthernetFramesTxOut0(value: &SW::SizedEthernetMessage_Impl) -> bool
{
  unsafe {
    return put_EthernetFramesTxOut0(value as *const SW::SizedEthernetMessage_Impl as *mut SW::SizedEthernetMessage_Impl);
  }
}

pub fn unsafe_put_EthernetFramesTxOut1(value: &SW::SizedEthernetMessage_Impl) -> bool
{
  unsafe {
    return put_EthernetFramesTxOut1(value as *const SW::SizedEthernetMessage_Impl as *mut SW::SizedEthernetMessage_Impl);
  }
}

pub fn unsafe_put_EthernetFramesTxOut2(value: &SW::SizedEthernetMessage_Impl) -> bool
{
  unsafe {
    return put_EthernetFramesTxOut2(value as *const SW::SizedEthernetMessage_Impl as *mut SW::SizedEthernetMessage_Impl);
  }
}

pub fn unsafe_put_EthernetFramesTxOut3(value: &SW::SizedEthernetMessage_Impl) -> bool
{
  unsafe {
    return put_EthernetFramesTxOut3(value as *const SW::SizedEthernetMessage_Impl as *mut SW::SizedEthernetMessage_Impl);
  }
}

//////////////////////////////////////////////////////////////////////////////////
// Testing Versions
//////////////////////////////////////////////////////////////////////////////////

#[cfg(test)]
lazy_static::lazy_static! {
  // simulate the global C variables that point to the microkit shared memory regions.  In a full
  // microkit system we would be able to mutate the shared memory for out ports since they're r/w,
  // but we couldn't do that for in ports since they are read-only
  pub static ref IN_EthernetFramesTxIn0: Mutex<Option<SW::RawEthernetMessage>> = Mutex::new(None);
  pub static ref IN_EthernetFramesTxIn1: Mutex<Option<SW::RawEthernetMessage>> = Mutex::new(None);
  pub static ref IN_EthernetFramesTxIn2: Mutex<Option<SW::RawEthernetMessage>> = Mutex::new(None);
  pub static ref IN_EthernetFramesTxIn3: Mutex<Option<SW::RawEthernetMessage>> = Mutex::new(None);
  pub static ref OUT_EthernetFramesTxOut0: Mutex<Option<SW::SizedEthernetMessage_Impl>> = Mutex::new(None);
  pub static ref OUT_EthernetFramesTxOut1: Mutex<Option<SW::SizedEthernetMessage_Impl>> = Mutex::new(None);
  pub static ref OUT_EthernetFramesTxOut2: Mutex<Option<SW::SizedEthernetMessage_Impl>> = Mutex::new(None);
  pub static ref OUT_EthernetFramesTxOut3: Mutex<Option<SW::SizedEthernetMessage_Impl>> = Mutex::new(None);
}

#[cfg(test)]
pub fn initialize_test_globals() {
  unsafe {
    *IN_EthernetFramesTxIn0.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_EthernetFramesTxIn1.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_EthernetFramesTxIn2.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_EthernetFramesTxIn3.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_EthernetFramesTxOut0.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_EthernetFramesTxOut1.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_EthernetFramesTxOut2.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_EthernetFramesTxOut3.lock().unwrap_or_else(|e| e.into_inner()) = None;
  }
}

#[cfg(test)]
pub fn get_EthernetFramesTxIn0(value: *mut SW::RawEthernetMessage) -> bool
{
  unsafe {
    match *IN_EthernetFramesTxIn0.lock().unwrap_or_else(|e| e.into_inner()) {
      Some(v) => {
        *value = v;
        return true;
      },
      None => return false,
    }
  }
}

#[cfg(test)]
pub fn get_EthernetFramesTxIn1(value: *mut SW::RawEthernetMessage) -> bool
{
  unsafe {
    match *IN_EthernetFramesTxIn1.lock().unwrap_or_else(|e| e.into_inner()) {
      Some(v) => {
        *value = v;
        return true;
      },
      None => return false,
    }
  }
}

#[cfg(test)]
pub fn get_EthernetFramesTxIn2(value: *mut SW::RawEthernetMessage) -> bool
{
  unsafe {
    match *IN_EthernetFramesTxIn2.lock().unwrap_or_else(|e| e.into_inner()) {
      Some(v) => {
        *value = v;
        return true;
      },
      None => return false,
    }
  }
}

#[cfg(test)]
pub fn get_EthernetFramesTxIn3(value: *mut SW::RawEthernetMessage) -> bool
{
  unsafe {
    match *IN_EthernetFramesTxIn3.lock().unwrap_or_else(|e| e.into_inner()) {
      Some(v) => {
        *value = v;
        return true;
      },
      None => return false,
    }
  }
}

#[cfg(test)]
pub fn put_EthernetFramesTxOut0(value: *mut SW::SizedEthernetMessage_Impl) -> bool
{
  unsafe {
    *OUT_EthernetFramesTxOut0.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}

#[cfg(test)]
pub fn put_EthernetFramesTxOut1(value: *mut SW::SizedEthernetMessage_Impl) -> bool
{
  unsafe {
    *OUT_EthernetFramesTxOut1.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}

#[cfg(test)]
pub fn put_EthernetFramesTxOut2(value: *mut SW::SizedEthernetMessage_Impl) -> bool
{
  unsafe {
    *OUT_EthernetFramesTxOut2.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}

#[cfg(test)]
pub fn put_EthernetFramesTxOut3(value: *mut SW::SizedEthernetMessage_Impl) -> bool
{
  unsafe {
    *OUT_EthernetFramesTxOut3.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}
